import Foundation

extension Strings {
    /// 英文翻译
    static let en = Strings(
        appTitle: "OmniForge",
        actionUnlock: "Unlock",
        actionLock: "Lock",
        actionQuit: "Quit",
        panelSelectSource: "Select input source to lock:",
        settingsLanguage: "Language",
        settingsSystem: "System Default",
        settingsLaunchAtLogin: "Launch at login",
        settingsHideDockIcon: "Hide Dock Icon",
        settingsAccessibility: "Accessibility Permission",
        settingsAccessibilityDescription: "Required to intercept input source switch shortcuts",
        settingsGrantAccess: "Grant Access",
        settingsDetectedHotkeys: "Detected Input Switch Hotkeys",
        settingsNoHotkeysDetected: "No hotkeys detected from system settings",
        settingsHotkeysNote: "These hotkeys are automatically read from your system settings. When locked, pressing these shortcuts will be blocked.",
        settingsGeneralSection: "General",
        settingsClipboardSection: "Clipboard History",
        settingsClipboardHotkey: "Clipboard Hotkey",
        settingsClipboardHotkeyRecording: "Press shortcut...",
        settingsClipboardRetentionDays: "Keep",
        settingsClipboardMaxEntries: "Max",
        settingsDays: "days",
        settingsEntries: "entries",
        settingsTabGeneral: "General",
        settingsTabInputMethod: "Input Method",
        settingsTabClipboard: "Clipboard",
        settingsTabMonitor: "Monitor",
        settingsTabMenuBar: "Menu Bar",
        settingsTabAlerts: "Alerts",
        settingsTabPerformance: "Performance",
        settingsTabShelf: "Shelf",
        settingsTabScreenshot: "Screenshot",
        settingsTabMouse: "Mouse",
        settingsTitle: "Settings",
        clipboardTitle: "Clipboard History",
        clipboardActionPaste: "Paste",
        clipboardSearch: "Type to filter...",
        clipboardEmpty: "No clipboard entries",
        clipboardPasteHint: "Paste to",
        clipboardPasteUnknown: "Active app",
        clipboardSectionToday: "Today",
        clipboardSectionYesterday: "Yesterday",
        clipboardSectionThisWeek: "This Week",
        clipboardSectionLastWeek: "Last Week",
        clipboardSectionThisMonth: "This Month",
        clipboardSectionThisYear: "This Year",
        clipboardDetail: "Details",
        clipboardDetailSource: "Source",
        clipboardDetailInformation: "Information",
        clipboardDetailType: "Content type",
        clipboardDetailDimensions: "Dimensions",
        clipboardDetailSize: "Image size",
        clipboardDetailCharacters: "Text statistics",
        clipboardDetailCharactersCount: "chars",
        clipboardDetailWordsCount: "words",
        clipboardDetailImageUnknown: "Unknown size",
        clipboardDetailTime: "Time",
        clipboardDetailUnavailable: "Preview unavailable",
        clipboardDetailRtf: "Rich text",
        clipboardFilterAll: "All Types",
        clipboardFilterText: "Text",
        clipboardFilterImage: "Image",
        clipboardFilterFile: "File",
        clipboardFilterUrl: "Link",
        clipboardFilterRtf: "Rich Text",
        clipboardFilterUnknown: "Unknown",
        controlcenterTabDashboard: "Main",
        controlcenterTabSettings: "Settings",
        controlcenterTabAccessibility: "Control center tab switch",
        controlcenterTabSystemMonitor: "System Monitor",
        controlcenterInputLockDescription: "Keep selected input source while locked",
        controlcenterInputLockNoSource: "No selectable input source available",
        controlcenterClipboardTitle: "Clipboard History",
        controlcenterClipboardEnabled: "Enabled, hotkey can open clipboard",
        controlcenterClipboardDisabled: "Disabled, hotkey will be ignored",
        controlcenterOpenSettings: "Settings",
        controlcenterTabUtilities: "Utilities",
        controlcenterNavMonitor: "Monitor",
        controlcenterNavKeepAwake: "Awake",
        controlcenterNavUtilities: "Tools",
        controlcenterEmpty: "No installed modules are available in Control Center.",
        runStateStopped: "Stopped",
        runStateRunning: "Running",
        runStateEnabled: "Enabled",
        runStateWaitingPermission: "Waiting for permission",
        runStateFailed: "Runtime error: %@",
        actionRetry: "Retry",
        permissionOpenSettings: "Open System Settings",
        utilityCleaner: "Cleaner",
        utilityUninstaller: "Uninstaller",
        utilityUninstallBusy: "Available after the current operation finishes",
        utilityCleanerSubtitle: "Clean leftovers, caches, logs, and trash",
        utilityUninstallerSubtitle: "Completely remove apps and related files",
        utilityColorPickerSubtitle: "Sample pixel colors from screen",
        utilityNetworkDiagnosticsSubtitle: "Inspect network identity and ports",
        utilityDSHWebSubtitle: "Start, stop, and restart dsh web",
        toolRetryFailures: "Retry Failed Items",
        toolSucceeded: "Succeeded",
        toolFailed: "Failed",
        toolScanFailure: "Could not scan %@: %@",
        monitorSettingsTitle: "Monitoring",
        monitorSettingsEnable: "Enable Monitoring",
        monitorSettingsRefreshInterval: "Refresh Interval",
        monitorSettingsTemperatureUnit: "Temperature Unit",
        monitorSettingsCelsius: "Celsius",
        monitorSettingsFahrenheit: "Fahrenheit",
        monitorPanelSectionsTitle: "Panel Sections",
        monitorSectionSystem: "System",
        monitorSectionNetwork: "Network",
        monitorSectionDisk: "Disk",
        monitorSectionPower: "Power",
        settingsMoveUp: "↑",
        settingsMoveDown: "↓",
        monitorMetricCpu: "CPU",
        monitorMetricGpu: "GPU",
        monitorMetricMemory: "Memory",
        monitorMetricCpuTemp: "CPU Temp",
        monitorMetricGpuTemp: "GPU Temp",
        monitorMetricDown: "Download",
        monitorMetricUp: "Upload",
        monitorMetricTotalDown: "Total Down",
        monitorMetricTotalUp: "Total Up",
        monitorMetricRead: "Read",
        monitorMetricWrite: "Write",
        monitorMetricFree: "Free",
        monitorMetricBattery: "Battery",
        monitorMetricCharging: "Charging",
        monitorValueYes: "Yes",
        monitorValueNo: "No",
        monitorMetricHealth: "Health",
        monitorMetricCycles: "Cycles",
        monitorMetricRemaining: "Remaining",
        monitorMetricSystemPower: "System Power",
        monitorMetricBatteryPower: "Battery Power",
        monitorIssueUnsupported: "Unsupported",
        monitorIssueFailed: "Failed",
        monitorNoDiskData: "No disk data",
        monitorNoPowerData: "No power data",
        monitorProcessLoading: "Loading %@…",
        monitorProcessUsage: "%@ Usage",
        monitorProcessEmpty: "No process data",
        monitorSpeedTestStart: "Run Speed Test",
        monitorSpeedTestRunning: "Testing…",
        monitorSpeedTestFailed: "Speed test failed",
        monitorDeviceFallbackName: "Mac",
        monitorStatusNormal: "Online",
        monitorStatusIssue: "Issue",
        monitorPreferences: "Preferences",
        monitorRefreshAll: "Refresh All",
        monitorCardStorage: "Storage",
        monitorCardDisk: "Disk",
        monitorCardNetworkTraffic: "Network",
        monitorCardDiskIO: "Disk I/O",
        monitorCardEnergy: "Energy",
        monitorLiveBadge: "Live",
        monitorProcessNameHeader: "Process Name",
        monitorProcessShareHeader: "Share",
        monitorRankingTitleCPU: "CPU Usage",
        monitorRankingTitleGPU: "GPU Usage",
        monitorRankingTitleMemory: "Memory Usage",
        monitorRankingTitleNetwork: "Network Usage",
        monitorRankingTitleEnergy: "Energy Usage",
        monitorFreeLabel: "Free",
        monitorOfTotal: "of %@",
        monitorSubtitleSeparator: "•",
        monitorPressureNormal: "OK",
        monitorPressureWarning: "WARN",
        monitorPressureCritical: "CRIT",
        monitorCPUSystem: "System",
        monitorCPUUser: "User",
        monitorUptimePrefix: "Uptime",
        monitorPowerSourceAdapter: "Power Adapter",
        monitorPowerSourceOnBattery: "On Battery",
        monitorDiskUsed: "Used",
        monitorCumulativeTotal: "Total",
        monitorMetricHealthShort: "Health",
        // Disk Detail
        diskSectionTitle: "Disk",
        diskSelect: "Select Disk",
        diskUsed: "used",
        diskFree: "free",
        diskInternal: "Internal",
        diskExternal: "External",
        diskRead: "Read",
        diskWrite: "Write",
        diskThisSession: "This Session",
        diskMeasuring: "Measuring",
        diskSMART: "SMART",
        diskSMARTStatus: "Status",
        diskTotalWritten: "Total Written",
        diskTotalRead: "Total Read",
        diskTemperature: "Temperature",
        diskHealth: "Health",
        diskPowerCycles: "Power Cycles",
        diskPowerOnHours: "Power-On Hours",
        diskSMARTUnavailable: "SMART unavailable for this disk",
        diskUnsupported: "Unsupported",
        diskProtection: "External Protection",
        diskEject: "Eject",
        diskEjectAll: "Eject All",
        diskEjecting: "Ejecting…",
        diskReadyToRemove: "Safe to remove",
        diskEjectFailed: "Eject failed",
        diskNoExternal: "No ejectable external disks.",
        diskProtectionCaption: "Eject before unplugging.",
        diskTools: "Tools",
        diskOpenInFinder: "Open",
        diskStorageSettings: "Storage",
        diskUsage: "Disk Usage",
        diskActivity: "Activity",
        diskNoDisks: "No mounted disks found",
        diskFileSystemUnsupported: "Unsupported",
        menubarSettingsEnable: "Show Metrics in Menu Bar",
        menubarSettingsTitle: "Menu Bar Metrics",
        menubarSettingsPreview: "Preview",
        menubarSettingsSpacing: "Spacing",
        menubarSettingsCompact: "Compact",
        menubarSettingsStandard: "Standard",
        menubarSettingsMemoryStyle: "Memory Style",
        menubarSettingsMemoryPercent: "Percent",
        menubarSettingsMemoryUsed: "Used",
        menubarSettingsMemoryPressure: "Pressure",
        menubarSettingsNetworkUploadFirst: "Show Upload First",
        menubarSettingsCombineTemperatures: "Combine Temperatures",
        menubarSettingsSeparateStatusItems: "Separate Status Items",
        menubarSettingsHideMainIcon: "Hide Main Icon",
        menubarMetricCPU: "CPU",
        menubarMetricGPU: "GPU",
        menubarMetricMemory: "Memory",
        menubarMetricNetwork: "Network",
        menubarMetricDisk: "Disk",
        menubarMetricPower: "Power",
        menubarMetricBattery: "Battery",
        menubarMetricCPUTemperature: "CPU Temperature",
        menubarMetricGPUTemperature: "GPU Temperature",
        menubarMetricBatteryTemperature: "Battery Temperature",
        menubarMetricPeripheralBattery: "Peripheral Battery",
        menubarMetricDate: "Date",
        settingsInputMethodSection: "Input Methods",
        alertsSettingsTitle: "Alerts",
        alertsCpu: "CPU Alert",
        alertsCpuTemperature: "CPU Temperature Alert",
        alertsMemory: "Memory Alert",
        alertsDisk: "Disk Alert",
        alertsBattery: "Battery Alert",
        alertsNotificationTitle: "Monitoring Alert",
        alertsBodyCpu: "CPU usage exceeded %d%%",
        alertsBodyCpuTemperature: "CPU temperature exceeded %d°",
        alertsBodyMemory: "Memory pressure is critical",
        alertsBodyDisk: "Disk free space below %d%%",
        alertsBodyBattery: "Battery level below %d%%",
        quickphraseSearchPlaceholder: "Search quick phrases...",
        menuAbout: "About OmniForge",
        menuSettings: "Settings…",
        menuHide: "Hide",
        menuHideOthers: "Hide Others",
        menuShowAll: "Show All",
        menuQuit: "Quit OmniForge",
        menuEdit: "Edit",
        menuUndo: "Undo",
        menuRedo: "Redo",
        menuCut: "Cut",
        menuCopy: "Copy",
        menuPaste: "Paste",
        menuSelectAll: "Select All",
        menuWindow: "Window",
        menuMinimize: "Minimize",
        menuZoom: "Zoom",
        menuClose: "Close",
        // Feature Hub
        settingsTabFeatures: "Features",
        settingsFeatureEnabled: "On",
        settingsFeatureDisabled: "Off",
        featureHubIntro: "Uninstall releases runtime objects immediately; data on disk is kept and reinstallable anytime.",
        featureHubTabFeatures: "Features",
        featureHubTabPermissions: "Permissions",
        featureHubActiveCount: "%d of %d installed",
        featureHubInstallAll: "Install All",
        featureHubUninstallAll: "Uninstall All",
        featureHubInstall: "Install",
        featureHubUninstall: "Uninstall",
        featureHubRestartNote: "Some features could not fully release in this session. Restart to finish unloading.",
        featureHubRestartButton: "Restart Now",
        featureHubNameInputLock: "Input Lock",
        featureHubNameClipboardHistory: "Clipboard History",
        featureHubNameQuickPhrase: "Quick Phrase",
        featureHubNameSystemMonitor: "System Monitor",
        featureHubNameNetworkDiagnostics: "Network Diagnostics",
        featureHubNameShelf: "Shelf",
        featureHubNameLaunchAtLogin: "Launch at Login",
        featureHubNameScrollInverter: "Invert Scroll",
        featureHubNameSmoothScroll: "Smooth Scrolling",
        featureHubNameMouseNavigation: "Mouse Navigation",
        featureHubNameDockClick: "Dock Click",
        featureHubNameKeepAwake: "Keep Awake",
        featureHubNameScreenshot: "Screenshot",
        featureHubNameDSHWeb: "DSH Web Service",
        featureHubDescInputLock: "Lock the input method so it stays put while typing.",
        featureHubDescClipboardHistory: "Save copied text locally for reuse.",
        featureHubDescQuickPhrase: "Store and paste frequently used text snippets.",
        featureHubDescSystemMonitor: "Track CPU, memory, disk and battery in the menu bar.",
        featureHubDescNetworkDiagnostics: "Inspect local network identity and port usage on demand.",
        featureHubDescShelf: "A floating spot to gather files, images and text, then drag them anywhere later.",
        featureHubDescLaunchAtLogin: "Start OmniForge automatically when you log in.",
        featureHubDescScrollInverter: "Reverse mouse wheel direction while keeping the trackpad natural.",
        featureHubDescSmoothScroll: "Turn discrete mouse wheel ticks into smooth glides.",
        featureHubDescMouseNavigation: "Map mouse side buttons to Back and Forward.",
        featureHubDescDockClick: "Taskbar-style Dock clicks to minimize, restore and cycle windows.",
        featureHubDescKeepAwake: "Prevent system and display sleep with timed sessions, low-battery protection, and optional lid-closed mode.",
        featureHubDescScreenshot: "Capture the screen, annotate, OCR, pin results, and manage pinned shots from the menu bar.",
        featureHubDescDSHWeb: "Start, stop and restart the dsh web service",
        featureHubGroupInput: "Input",
        featureHubGroupClipboard: "Clipboard & Snippets",
        featureHubGroupMonitor: "System Monitor",
        featureHubGroupProductivity: "Productivity",
        featureHubGroupSystem: "System",
        featureHubGroupMouse: "Mouse & Trackpad",
        featureHubGroupEnergy: "Energy",
        featureHubGroupCapture: "Capture",
        featureHubPermissionsIntro: "See what each permission does and which features need it.",
        featureHubPermStatusGranted: "Granted",
        featureHubPermStatusMissing: "Not Granted",
        featureHubPermUsedBy: "Used by",
        featureHubPermUsedByNone: "No installed feature needs this permission.",
        featureHubPermUsageRequired: "Required",
        featureHubPermUsageConfigured: "Configured",
        featureHubPermUsageOptional: "Optional",
        featureHubPermUsageInactive: "Not in use",
        featureHubPermOpenSettings: "Open System Settings",
        featureHubPermRefresh: "Check Again",
        featureHubPermRecoveryHint: "If permission is enabled but not effective, quit OmniForge and enable it again, or remove and re-add the currently installed app.",
        featureHubPermSignature: "Current signature",
        featureHubPermNameAccessibility: "Accessibility",
        featureHubPermNameInputMonitoring: "Input Monitoring",
        featureHubPermNameNotifications: "Notifications",
        featureHubPermDescAccessibility: "Lets OmniForge intercept input method switch shortcuts.",
        featureHubPermDescInputMonitoring: "Lets OmniForge read keyboard events to detect hotkeys.",
        featureHubPermDescNotifications: "Lets the system monitor send you alerts.",
        featureHubPermNameFullDiskAccess: "Full Disk Access",
        featureHubPermDescFullDiskAccess: "Lets the uninstaller and cleaner scan protected locations for leftover and junk files.",
        featureHubPermNameScreenRecording: "Screen Recording",
        featureHubPermDescScreenRecording: "Lets OmniForge capture the screen for screenshots, annotations, and region recording.",
        // Onboarding
        onboardingWelcomeTitle: "Welcome to OmniForge",
        onboardingWelcomeBody: "Lock input methods, manage clipboard history, quick phrases, and system monitoring — all from your menu bar.",
        onboardingNext: "Next",
        onboardingBack: "Back",
        onboardingFinish: "Finish",
        onboardingSkip: "Skip",
        onboardingPermissionsTitle: "Permissions",
        onboardingPermissionsBody: "OmniForge needs the following permissions to work properly. You can change these later in System Settings.",
        onboardingPermissionAccessibility: "Accessibility",
        onboardingPermissionAccessibilityDescription: "Required to intercept input method switching shortcuts",
        onboardingPermissionNotifications: "Notifications",
        onboardingPermissionNotificationsDescription: "Required for system monitor alerts and important reminders",
        onboardingGrantPermission: "Grant",
        onboardingPermissionGranted: "Granted",
        onboardingRecheck: "Recheck",
        onboardingPermissionHint: "If the app restarts after granting permissions, the wizard resumes from the current step.",
        onboardingFeaturesTitle: "Features",
        onboardingFeaturesBody: "Here are all features provided by OmniForge. You can enable or disable them anytime in Settings.",
        onboardingFeatureInputLockTitle: "Input Lock",
        onboardingFeatureInputLockDescription: "Lock the current input method to prevent accidental switching",
        onboardingFeatureClipboardHistoryTitle: "Clipboard History",
        onboardingFeatureClipboardHistoryDescription: "Automatically record clipboard content with search and paste",
        onboardingFeatureQuickPhraseTitle: "Quick Phrase",
        onboardingFeatureQuickPhraseDescription: "Save frequent phrases and insert them into any app",
        onboardingFeatureSystemMonitorTitle: "System Monitor",
        onboardingFeatureSystemMonitorDescription: "Monitor CPU, memory, disk and network in real time",
        onboardingFeatureShelfTitle: "Shelf",
        onboardingFeatureShelfDescription: "A floating spot to gather files, images and text, then drag them anywhere later",
        onboardingFeatureLaunchAtLoginTitle: "Launch at Login",
        onboardingFeatureLaunchAtLoginDescription: "Start OmniForge automatically when you log in",
        onboardingDoneTitle: "Setup Complete",
        onboardingDoneHint: "Click the menu bar icon to start using OmniForge. You can change settings anytime.",
        // What's New
        whatsNewTitle: "What's New",
        whatsNewClose: "Close",
        // Shelf
        shelfName: "Shelf",
        shelfEnable: "Temporary area for dragging files",
        shelfEnableCaption: "A floating spot to gather files, images and text, then drag them anywhere later.",
        shelfHowTitle: "How to use",
        shelfStep1: "Open it with the shortcut, or by shaking the mouse during a drag.",
        shelfStep2: "Drop files, images, links or text onto it to hold them.",
        shelfStep3: "Drag each item back out to any app when you need it.",
        shelfShakeToggle: "Open by shaking the mouse while dragging",
        shelfShakeCaption: "Shake the pointer quickly while holding an item to summon it near the cursor.",
        shelfDropZoneToggle: "Keep dragged files in the menu bar",
        shelfDropZoneCaption: "While you drag a file, the shelf appears below the menu bar icon. Whatever you drop is kept right there, in a button you shrink and open with a click that goes away once the shelf is empty.",
        shelfDropZoneLabel: "Drop here",
        shelfCollapse: "Collapse",
        shelfBehaviorTitle: "After use",
        shelfCloseAfterDrop: "Close after dropping into another app",
        shelfCloseAfterDropCaption: "Closes the shelf when the destination accepts the items. The pin in the panel keeps it open.",
        shelfRemoveAfterDrop: "Remove items after dropping",
        shelfRemoveAfterDropCaption: "Items accepted by another app leave the shelf. Turn this off to keep a copy there.",
        shelfExclusionsTitle: "Automatic exceptions",
        shelfExclusionsEmpty: "No apps added.",
        shelfExclusionsCaption: "Shake and the menu bar drop zone stay off for drags started in these apps. The shortcut and Open now still work.",
        shelfPin: "Keep open",
        shelfUnpin: "Allow closing after use",
        shelfHotkeyLabel: "Shortcut",
        shelfOpenNow: "Open now",
        shelfNoPermission: "Requires no permissions.",
        shelfMenuItem: "Open shelf",
        shelfTitle: "Shelf",
        shelfEmpty: "Drag items here",
        shelfClearAll: "Clear all",
        shelfRemoveSelected: "Remove selected",
        shelfSelectedFormat: "%d selected",
        shelfHint: "Click to select. Drag out to use or right-click for more actions.",
        shelfItemImage: "Image",
        shelfActionOpen: "Open",
        shelfActionOpenWith: "Open With",
        shelfActionAirDrop: "Share with AirDrop",
        shelfActionReveal: "Reveal in Finder",
        shelfShortcutToggle: "Shelf shortcut",
        shelfFeatureUnavailable: "Install Shelf from Features to use these settings.",
        shelfAddApp: "Add app…",
        shelfAppPickerTitle: "Choose an App",
        shelfAppPickerSearch: "Search",
        shelfAppPickerCancel: "Cancel",
        shelfAppPickerEmpty: "No apps found.",
        // Uninstaller
        uninstallerName: "Uninstaller",
        uninstallerEnableCaption: "Removes an app together with the caches, preferences, logs and leftovers it leaves behind.",
        uninstallerDropTitle: "Drag an app here",
        uninstallerDropSubtitle: "or choose one to scan",
        uninstallerChoose: "Choose app…",
        uninstallerPickerTitle: "Choose app",
        uninstallerPickerSearch: "Search apps",
        uninstallerPickerEmpty: "No apps found",
        uninstallerEmptyNote: "Nothing is removed without your confirmation.",
        uninstallerFDANote: "Grant Full Disk Access for a more thorough scan.",
        uninstallerFDAGrant: "Grant access…",
        uninstallerFDAHint: "Turn OmniForge on in the list. If it isn't there, click + and pick OmniForge from Applications. Access only applies after you reopen the app.",
        uninstallerFDARelaunch: "Relaunch now",
        uninstallerScanning: "Scanning files…",
        uninstallerRemoving: "Moving to the Trash…",
        uninstallerFoundTitle: "found",
        uninstallerSelectedFormat: "%d of %d selected",
        uninstallerRemove: "Move to Trash",
        uninstallerCancel: "Cancel",
        uninstallerDoneTitle: "Done!",
        uninstallerFreedFormat: "%@ recovered",
        uninstallerSomeFailed: "Some items couldn't be moved to the Trash.",
        uninstallerAnother: "Uninstall another",
        uninstallerCatApp: "Application",
        uninstallerCatSupport: "Support",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Preferences",
        uninstallerCatContainers: "Containers",
        uninstallerCatLogs: "Logs",
        uninstallerCatState: "Saved state",
        uninstallerCatOther: "Other",
        // Color Picker
        colorPickerName: "Color Picker",
        colorPickerDescription: "Pick a color from anywhere on screen. HEX / RGB / HSL supported.",
        colorPickerIntroTitle: "Pick a screen color",
        colorPickerIntroCaption: "Tap the button below, move the loupe to any spot, then click to confirm. Press ESC to cancel.",
        colorPickerStart: "Start Picking",
        colorPickerInProgress: "Click a color on screen…",
        colorPickerPickAgain: "Pick Again",
        colorPickerFormatHex: "HEX",
        colorPickerFormatRGB: "RGB",
        colorPickerFormatHSL: "HSL",
        // Network Diagnostics
        networkDiagnosticsSegmentNetwork: "Network",
        networkDiagnosticsSegmentPorts: "Ports",
        networkDiagnosticsRefresh: "Refresh",
        networkDiagnosticsCopy: "Copy",
        networkDiagnosticsValueUnavailable: "—",
        networkDiagnosticsHostSection: "Host",
        networkDiagnosticsHostname: "Hostname",
        networkDiagnosticsInterfacesSection: "Interfaces",
        networkDiagnosticsInterfaceIPv4: "IPv4",
        networkDiagnosticsInterfaceIPv6: "IPv6",
        networkDiagnosticsInterfaceMAC: "MAC",
        networkDiagnosticsRouteSection: "Default Route",
        networkDiagnosticsGateway: "Gateway",
        networkDiagnosticsRouteInterface: "Interface",
        networkDiagnosticsDNSSection: "DNS",
        networkDiagnosticsDNSServers: "DNS Servers",
        networkDiagnosticsPublicIPSection: "Public IP",
        networkDiagnosticsPublicIPv4: "Public IPv4",
        networkDiagnosticsPublicIPv6: "Public IPv6",
        networkDiagnosticsPublicIPLoading: "Looking up…",
        networkDiagnosticsNetworkEmpty: "No network information",
        networkDiagnosticsNetworkLoadFailed: "Failed to load network information",
        networkDiagnosticsSearchPlaceholder: "Search port / process…",
        networkDiagnosticsScopeListen: "LISTEN",
        networkDiagnosticsScopeAll: "All",
        networkDiagnosticsColumnProtocol: "Protocol",
        networkDiagnosticsColumnLocalPort: "Local Port",
        networkDiagnosticsColumnProcess: "Process (PID)",
        networkDiagnosticsColumnStatus: "Status",
        networkDiagnosticsPortsEmpty: "No connections",
        networkDiagnosticsPortsEmptyListen: "No listening ports",
        networkDiagnosticsPortsLoadFailed: "Failed to collect port information",
        networkDiagnosticsPortsLoadFailedBanner: "Collection failed. Copy a terminal command to inspect manually.",
        networkDiagnosticsPartialPermissionBanner: "Some details need higher privileges to display",
        networkDiagnosticsCopyTerminalCommand: "Copy Terminal Command",
        networkDiagnosticsShowCommand: "Show Command",
        networkDiagnosticsHideCommand: "Hide Command",
        networkDiagnosticsCopyHostPort: "Copy host:port",
        networkDiagnosticsCopyPID: "Copy PID",
        networkDiagnosticsCopyProcessName: "Copy Process Name",
        networkDiagnosticsCopySudoKill: "Copy sudo kill Command",
        networkDiagnosticsCopySudoKill9: "Copy sudo kill -9 Command",
        networkDiagnosticsTerminateProcess: "Terminate Process",
        networkDiagnosticsTerminateTitle: "Terminate Process?",
        networkDiagnosticsTerminateMessageFormat: "Send a terminate signal (SIGTERM) to %@ (PID %d, port %d).",
        networkDiagnosticsTerminateConfirm: "Terminate",
        networkDiagnosticsTerminateCancel: "Cancel",
        networkDiagnosticsTerminateSuccess: "Terminate signal sent",
        networkDiagnosticsAlertOK: "OK",
        networkDiagnosticsProcessGone: "Process is no longer running",
        networkDiagnosticsForceTerminateTitle: "Force Terminate?",
        networkDiagnosticsForceTerminateMessage: "SIGTERM did not end this process. Send SIGKILL?",
        networkDiagnosticsForceTerminateConfirm: "Force Terminate",
        networkDiagnosticsTerminateFailed: "Could not terminate the process. Copy a sudo command to run in Terminal.",
        networkDiagnosticsProtectedProcess: "Protected system process cannot be terminated",
        networkDiagnosticsUnknownProcess: "Unknown process",
        dshWebStart: "Start",
        dshWebStop: "Stop",
        dshWebRestart: "Restart",
        dshWebOpenBrowser: "Open in Browser",
        dshWebStateRunning: "Running",
        dshWebStateStopped: "Stopped",
        dshWebStateStarting: "Starting…",
        dshWebStateStopping: "Stopping…",
        dshWebStateFailed: "Failed: %@",
        dshWebPortOccupied: "Port 3080 is already in use; dsh web or another service may be running",
        dshWebPortOccupiedFormat: "Port %d is already in use; dsh web or another service may be running",
        dshWebStartTimeout: "Startup timed out; the service did not become ready",
        dshWebLaunchFailed: "Failed to launch the dsh web process",
        dshWebLogTitle: "Log",
        dshWebLogEmpty: "No log entries yet",
        dshWebCopyLog: "Copy",
        dshWebClearLog: "Clear",
        dshWebPort: "Port",
        dshWebRefresh: "Refresh",
        dshWebServicesTitle: "Discovered Services",
        dshWebExternalServicesTitle: "Discovered External Services",
        dshWebNoServices: "No running DSH Web services found",
        dshWebManagedService: "Started by this app",
        dshWebExternalService: "Started externally",
        dshWebStopExternalTitle: "Stop external DSH Web service?",
        dshWebStopExternalMessageFormat: "This will stop the externally started DSH Web service at PID %d on port %d.",
        dshWebCancel: "Cancel",
        networkDiagnosticsProcessPIDFormat: "%@ (%d)",
        // Cleaner
        cleanerName: "Cleaner",
        cleanerIntroTitle: "Clean up your Mac",
        cleanerIntroCaption: "Scans for leftovers from uninstalled apps, caches, logs and the Trash. You review everything first and removed items go to the Trash.",
        cleanerScan: "Scan",
        cleanerScanning: "Scanning…",
        cleanerScanProgressFormat: "%d candidates checked · %d found · %@",
        cleanerCleaning: "Cleaning…",
        cleanerCatLeftovers: "Leftovers from uninstalled apps",
        cleanerCatLoginItems: "Orphaned startup items",
        cleanerCatCaches: "Caches",
        cleanerCatLogs: "Logs",
        cleanerCatDeveloper: "Developer junk",
        cleanerCatTrash: "Trash",
        cleanerLeftoversNote: "Found by analysis and left unchecked. Check the path before ticking.",
        cleanerLoginItemsNote: "The entry under Login Items disappears after restarting the Mac.",
        cleanerTrashNote: "Emptying the Trash is permanent.",
        cleanerCatDeviceBackups: "iPhone backups",
        cleanerDeviceBackupsCaption: "Old iPhone and iPad backups take a big slice of the storage macOS calls Other. Remove only the ones you no longer need; a new backup is made when you plug the device in again.",
        cleanerNothingFound: "Nothing to clean. Your Mac is tidy.",
        cleanerClean: "Clean",
        cleanerDoneNote: "Items went to the Trash and can be recovered from there.",
        cleanerAgain: "Scan again",
        cleanerRevealInFinder: "Reveal in Finder",
        cleanerSafeSection: "Safe cleanup",
        cleanerOptionalSection: "Optional, review first",
        cleanerCatOtherCaches: "Other caches",
        cleanerCachesCaption: "Temporary files apps rebuild on their own.",
        cleanerLogsCaption: "Old diagnostic logs.",
        cleanerDeveloperCaption: "Xcode build and simulator leftovers.",
        cleanerLoginItemsCaption: "Startup entries left by apps that no longer exist.",
        cleanerLeftoversCaption: "Files left behind by apps you uninstalled.",
        cleanerOtherCachesCaption: "Safe to remove, nothing breaks. Apps may open slower once and downloaded content, like offline music, downloads again.",
        cleanerCleanSizeFormat: "Clean %@",
        cleanerScheduleTitle: "Automatic cleanup",
        cleanerScheduleOff: "Off",
        cleanerScheduleDaily: "Daily",
        cleanerScheduleWeekly: "Weekly",
        cleanerScheduleCaption: "Cleans only the safe part on its own at the chosen time and sends everything to the Trash.",
        cleanerScheduleLastFormat: "The last automatic cleanup freed %@.",
        cleanerAutoNotificationFormat: "%@ freed and sent to the Trash.",
        cleanerScheduleNextFormat: "Next cleanup %@.",
        cleanerScheduleRanFormat: "Last automatic cleanup %@.",
        cleanerScheduleNotifyToggle: "Notify when done",
        cleanerNotifDenied: "OmniForge notifications are turned off in the system.",
        cleanerNotifOpenSettings: "Open Notification Settings…",

        // MARK: - Mouse & Trackpad
        scrollSection: "Scrolling",
        invertMouseScroll: "Invert mouse wheel direction",
        invertMouseScrollCaption: "Mouse wheels scroll the opposite way, like older macOS versions. The trackpad keeps natural scrolling.",
        scrollTrackpadNote: "Only real mouse wheels are affected; trackpads, Magic Mouse and momentum pass through untouched.",
        scrollActiveNow: "Inverting now",
        smoothScrollName: "Smooth scrolling",
        smoothScrollCaption: "Turn discrete mouse wheel ticks into smooth glides.",
        smoothScrollStepLabel: "Pixels per tick",
        mouseNavigationSection: "Side Buttons",
        mouseNavigationEnable: "Use side buttons for Back and Forward",
        mouseNavigationCaption: "The Back and Forward side buttons trigger the matching app command (such as Finder and browser navigation).",
        mouseNavigationActiveNow: "Active",
        dockClickSection: "Dock",
        dockClickMinimize: "Click the active app's Dock icon to minimize",
        dockClickMinimizeCaption: "Clicking the Dock icon of the frontmost app minimizes its windows, like a taskbar.",
        dockClickCycleWindows: "Click the active app's Dock icon to cycle windows",
        dockClickCycleWindowsCaption: "When the app has multiple windows, each click of its Dock icon brings the next one forward.",
        permissionRequired: "Permission Required",
        keepAwakeTitle: "Keep Awake",
        keepAwakeDurationLabel: "Awake Duration",
        keepAwakeDurationNever: "Never",
        keepAwakeDuration15m: "15 min",
        keepAwakeDuration1h: "1 hour",
        keepAwakeDuration4h: "4 hours",
        keepAwakeClamshellTitle: "Keep Awake when Closed",
        keepAwakeClamshellSubtitle: "Power adapter required",
        keepAwakeClamshellFootnote: "When enabled, the display will stay on when the lid is closed",
        keepAwakeStatusCurrentPrefix: "Current: %@",
        keepAwakeOptionsSection: "Options",
        keepAwakeRemainingLabel: "Remaining",
        keepAwakeEndsAtLabel: "Ends at",
        keepAwakeOpenSettingsHint: "Open Keep Awake Settings to configure authorization",
        keepAwakeClamshellCaption: "May require administrator password once",
        keepAwakeStart: "Start",
        keepAwakeStop: "Stop",
        keepAwakeRetryCleanup: "Retry Cleanup",
        keepAwakeUnavailable: "Unavailable",
        keepAwakeStatusFeatureUnavailable: "Feature unavailable",
        keepAwakeStatusWaitingRecovery: "Waiting for clamshell recovery",
        keepAwakeStatusNormalSleep: "Normal sleep",
        keepAwakeStatusNotActiveWithError: "Not active — %@",
        keepAwakeStatusStarting: "Starting…",
        keepAwakeStatusActiveTimed: "Active until scheduled end",
        keepAwakeStatusActiveIndefinite: "Active indefinitely",
        keepAwakeStatusStopping: "Stopping…",
        keepAwakeStatusCleanupRequired: "Cleanup required — sleep may not be restored",
        keepAwakeClamshellChecking: "Clamshell: checking",
        keepAwakeClamshellAuthorizing: "Clamshell: authorizing",
        keepAwakeClamshellEnabling: "Clamshell: enabling",
        keepAwakeClamshellActive: "Clamshell: active",
        keepAwakeClamshellRestoring: "Clamshell: restoring",
        keepAwakeClamshellConflict: "Clamshell: conflict",
        keepAwakeClamshellFailed: "Clamshell: failed",
        keepAwakeRecoveryCheckingTitle: "Checking clamshell recovery",
        keepAwakeRecoveryCheckingDetail: "Verifying SleepDisabled and recovery record…",
        keepAwakeRecoveryRestoringTitle: "Restoring system sleep",
        keepAwakeRecoveryRestoringDetail: "Running restricted pmset recovery…",
        keepAwakeRecoveryCleanupTitle: "Clamshell cleanup required",
        keepAwakeRecoveryConflictTitle: "Clamshell recovery conflict",
        keepAwakeRetry: "Retry",
        keepAwakeMenuStartDefault: "Start with default duration",
        keepAwakeMenuRetryLastStart: "Retry last start",
        keepAwakeMenuStartDuration: "Start duration",
        keepAwakeMenuProcessing: "Working…",
        keepAwakeMenuStop: "Stop Keep Awake",
            keepAwakeMenuRetryCleanup: "Retry cleanup",
            keepAwakeMenuOpenSettings: "Open Keep Awake Settings",
            keepAwakeClamshellAction: "Clamshell Keep Awake",
            keepAwakeMenuQuit: "Quit OmniForge",
        keepAwakeTooltipInactive: "Normal sleep",
        keepAwakeTooltipInactiveWithError: "Keep Awake off — %@",
        keepAwakeTooltipActivating: "Starting Keep Awake",
        keepAwakeTooltipDeactivating: "Stopping Keep Awake",
        keepAwakeTooltipActiveTimed: "Keep Awake until %@",
        keepAwakeTooltipActiveIndefinite: "Keep Awake indefinitely",
        keepAwakeTooltipCleanupRequired: "Cleanup required",
        keepAwakeNotificationTitle: "Keep Awake",
        keepAwakeAuthDisclosureTitle: "Configure clamshell authorization",
        keepAwakeAuthDisclosureBody: "Authorization installs a NOPASSWD sudoers rule for this user with only two exact pmset commands. Other processes under the same user can run those commands. pmset disablesleep is undocumented and not guaranteed. Recovery after abnormal exit happens on next OmniForge launch, not immediately after a crash. Uninstalling the feature does not remove the rule.",
        keepAwakeAuthContinue: "Continue and enter admin password",
        keepAwakeAuthRemoveTitle: "Remove clamshell authorization",
        keepAwakeAuthRemoveBody: "This deletes the current user's restricted sudoers rule. System sleep must already be restored (SleepDisabled=0).",
        keepAwakeAuthRemove: "Remove",
        keepAwakeAuthCancel: "Cancel",
        keepAwakeSectionSession: "Session",
        keepAwakeDefaultDuration: "Default duration",
        keepAwakeDurationIndefinite: "Indefinite",
        keepAwakeDurationMinutesFormat: "%d min",
        keepAwakeDurationHoursFormat: "%d h",
        keepAwakeAutoStart: "Auto-start on launch",
        keepAwakeSectionBattery: "Battery protection",
        keepAwakeBatteryThreshold: "Low-battery threshold",
        keepAwakeBatteryOff: "Off",
        keepAwakeBatteryPercentFormat: "%d%%",
        keepAwakeBatteryCaption: "Ends the session and restores sleep when the threshold is reached.",
        keepAwakeSectionMenuBar: "Menu bar",
        keepAwakeShowCountdown: "Show countdown",
        keepAwakeSectionShortcut: "Shortcut",
        keepAwakeEnableShortcut: "Enable global shortcut",
        keepAwakeHotkeyManagerMissing: "Hotkey manager not loaded",
        keepAwakeRecord: "Record",
        keepAwakeCancelRecording: "Cancel recording",
        keepAwakeSectionPointer: "Pointer jiggle",
        keepAwakeEnableJiggle: "Enable pointer jiggle",
        keepAwakeJiggleInterval: "Jiggle interval",
        keepAwakeJiggleCaption: "Requires Accessibility permission; the system prompt appears only when you request it.",
        keepAwakeRequestAccessibility: "Request Accessibility permission",
        keepAwakeSectionClamshell: "Clamshell",
        keepAwakePreferClamshell: "Prefer running with lid closed",
        keepAwakeCapabilityPrefix: "Current capability",
        keepAwakeCapabilityChecking: "Checking",
        keepAwakeCapabilityUnsupportedFormat: "Unsupported (%@)",
        keepAwakeCapabilityNeedsAuth: "Authorization required",
        keepAwakeCapabilityReady: "Ready",
        keepAwakeCapabilityConflictFormat: "Conflict (%@)",
        keepAwakeCapabilityInvalidFormat: "Invalid authorization (%@)",
        keepAwakeConfigureAuth: "Configure / retry authorization",
        keepAwakeRemoveAuth: "Remove authorization",
        keepAwakeRefreshStatus: "Refresh status",
        keepAwakeSectionDiagnostics: "Diagnostics",
        keepAwakeDiagSessionFormat: "Session: %@",
        keepAwakeDiagClamshellFormat: "Clamshell: %@",
        keepAwakeDiagErrorFormat: "Last error: %@",
        keepAwakeDiagManagerMissing: "Manager not loaded",
        keepAwakeDiagRecoveryFormat: "Recovery: %@",
        keepAwakeRecoveryIdle: "Not required",
        keepAwakeRecoveryRecovered: "Recovered",
        keepAwakeAuthInstallSuccess: "Authorization installed",
        keepAwakeAuthRemoveSuccess: "Authorization removed",
        keepAwakeAuthManagerMissingInstall: "Manager not loaded; cannot install authorization",
        keepAwakeAuthNoRemoveEntry: "No authorization removal entry available",
        keepAwakeErrCancelled: "Administrator authorization cancelled",
        keepAwakeErrSudoersFormat: "Sudoers validation failed: %@",
        keepAwakeErrRemovalFormat: "Failed to remove authorization: %@",
        keepAwakeErrBusy: "Operation in progress, retry shortly",
        keepAwakeErrClamshellUnsupportedFormat: "Clamshell unavailable: %@",
        keepAwakeNotifDurationElapsed: "Session ended after the scheduled duration.",
        keepAwakeNotifLowBattery: "Session ended because battery reached the limit.",
        keepAwakeNotifCleanupDuration: "Session ended, but system sleep may not be fully restored.",
        keepAwakeNotifCleanupLowBattery: "Session ended for low battery, but system sleep may not be fully restored.",
        featureHubRetryUninstall: "Retry",
        featureHubUninstallFailedFormat: "Uninstall failed: %@",
        screenshotEnable: "Enable Screenshot",
        screenshotEnableCaption: "When enabled, global screenshot hotkeys are active while the feature is installed.",
        screenshotPermissionSection: "Screen Recording Permission",
        screenshotPermissionCaption: "Screen Recording is required before any capture can start. Denied requests fail visibly.",
        screenshotRequestPermission: "Request Screen Recording",
        screenshotHotkeysSection: "Hotkeys",
        screenshotHotkeyAllInOne: "All-in-One Capture",
        screenshotHotkeyCopy: "Capture and Copy",
        screenshotHotkeyPin: "Capture and Pin",
        screenshotHotkeyFullscreen: "Fullscreen",
        screenshotHotkeyRecord: "Screen Recording",
        screenshotOutputSection: "Output",
        screenshotSaveDirectory: "Save folder",
        screenshotChooseDirectory: "Choose Folder…",
        screenshotPermissionDenied: "Screen Recording permission is not granted. Open System Settings to allow capture.",
        screenshotHotkeyIgnoredNotListening: "Screenshot hotkeys are not listening.",
        screenshotHotkeyIgnoredUnavailable: "Screenshot feature is not installed or unavailable.",
        recordingSection: "Screen Recording",
        recordingSaveDirectory: "Recording save folder",
        recordingChooseDirectory: "Choose Folder…",
        recordingFormatPreference: "Save format",
        recordingFormatManual: "Ask each time",
        recordingFormatMP4: "MP4",
        recordingFormatGIF: "GIF",
        recordingFormatLabel: "Format",
        recordingFormatChoiceTitle: "Save recording",
        recordingFormatChoiceMessage: "Choose the export format for this recording.",
        recordingSavePrompt: "Save",
        recordingCancelPrompt: "Cancel",
        recordingStop: "Stop",
        recordingPause: "Pause",
        recordingResume: "Resume",
        recordingCancelled: "Recording cancelled.",
        recordingExportingGIF: "Exporting GIF…",
        recordingSavedFormat: "Recording saved to %@",
        recordingFailedFormat: "Recording failed: %@",
        screenshotMenuTitle: "Screenshot",
        pinnedMenuTitle: "Pinned Screenshots",
        pinnedMenuEmpty: "No pinned screenshots",
        pinnedMenuCopy: "Copy",
        pinnedMenuSave: "Save",
        pinnedMenuEnableClickThrough: "Enable Click-Through",
        pinnedMenuDisableClickThrough: "Disable Click-Through",
        pinnedMenuLock: "Lock",
        pinnedMenuUnlock: "Unlock",
        pinnedMenuClose: "Close",
        pinnedMenuCloseAll: "Close All Pins",
        pinnedMenuActionFailedFormat: "Pinned screenshot action failed: %@",
        screenshotSessionAlreadyActive: "Capture session is already active.",
        screenshotTargetDisplayUnavailable: "Target display is unavailable.",
        screenshotModeNotImplementedFormat: "Screenshot mode not implemented: %@",
        screenshotCaptureFailedFormat: "Capture failed: %@",
        screenshotInvalidResultFormat: "Invalid capture result: %@",
        screenshotInvalidSelectionFormat: "Invalid selection: %@",
        screenshotPipelineFailedFormat: "Result pipeline failed: %@",
        screenshotElementRoleWindow: "Window",
        screenshotElementRoleButton: "Button",
        screenshotElementRoleMenu: "Menu",
        screenshotElementRoleMenuItem: "Menu Item",
        screenshotElementRoleTextField: "Text Field",
        screenshotElementRoleSearchField: "Search Field",
        screenshotElementRoleTab: "Tab",
        screenshotElementRoleCheckbox: "Checkbox",
        screenshotElementRoleRadioButton: "Radio Button",
        screenshotElementRoleSlider: "Slider",
        screenshotElementRoleListItem: "List Item",
        screenshotElementRoleCell: "Cell",
        screenshotElementRoleToolbarItem: "Toolbar Item",
        screenshotElementRoleGroup: "Group",
        screenshotElementRoleScrollArea: "Scroll Area",
        screenshotElementRoleImage: "Image",
        screenshotElementRoleUnknown: "UI Element",
        screenshotElementAccessibilityPermissionMissing: "Accessibility permission missing — only window snap and manual selection are supported",
        screenshotElementTargetUnavailable: "Target element unavailable — only window snap and manual selection are supported",
        screenshotElementDetectionFailedFormat: "Element detection failed: %@",
        screenshotFileNamePrefixLabel: "File name prefix",
        screenshotFileNamePrefixCaption: "Used as the saved file name prefix (timestamp and duplicate index are kept).",
        screenshotFileNamePrefixInvalid: "File name prefix must not be empty or contain path separators.",
        screenshotCustomPresetsSection: "Custom region presets",
        screenshotCustomPresetsCaption: "Added presets join the built-in list cycled with R / Shift+R. Fixed sizes that exceed the current screen are skipped at capture time.",
        screenshotPresetAspectWidth: "Aspect W",
        screenshotPresetAspectHeight: "Aspect H",
        screenshotPresetAddAspect: "Add aspect ratio",
        screenshotPresetFixedWidth: "Fixed W (px)",
        screenshotPresetFixedHeight: "Fixed H (px)",
        screenshotPresetAddFixed: "Add fixed size",
        screenshotPresetRemove: "Remove",
        screenshotPresetInvalidInput: "Width and height must be positive integers.",
        screenshotPinMenuCopy: "Copy",
        screenshotPinMenuSave: "Save",
        screenshotPinMenuLock: "Lock",
        screenshotPinMenuUnlock: "Unlock",
        screenshotPinMenuClickThrough: "Click Through",
        screenshotPinMenuDisableClickThrough: "Disable Click Through",
        screenshotPinMenuOpacity: "Opacity",
        screenshotPinMenuClose: "Close",
        screenshotOverlayPresetFree: "Free",
        screenshotOverlayFixedExceedsFormat: "Fixed size %d×%d px exceeds this display (%d×%d pt @%.1fx).",
        screenshotOverlayFixedDoesNotFit: "Fixed size does not fit this display.",
        annotationWindowTitle: "Annotate Screenshot",
        annotationToolSelect: "Select",
        annotationToolArrow: "Arrow",
        annotationToolLine: "Line",
        annotationToolRectangle: "Rectangle",
        annotationToolEllipse: "Ellipse",
        annotationToolText: "Text",
        annotationToolFreehand: "Freehand",
        annotationToolMosaic: "Mosaic",
        annotationToolBlur: "Blur",
        annotationToolRedaction: "Redact",
        annotationRedactionModePixelate: "Pixelate",
        annotationRedactionModeBlur: "Blur",
        annotationRedactionModeSolid: "Solid",
        annotationToolHighlighter: "Highlighter",
        annotationToolCounter: "Number",
        annotationToolCrop: "Crop",
        annotationCropHint: "Drag handles to adjust crop. Confirm writes non-destructive crop.",
        annotationCropConfirm: "Confirm Crop",
        annotationCropCancel: "Cancel Crop",
        annotationCropClear: "Clear Crop",
        annotationCropPreset: "Crop ratio",
        annotationCropPresetFreeform: "Freeform",
        annotationCropPresetOriginal: "Original ratio",
        annotationCropPresetSquare: "1:1 Square",
        annotationCropPreset4x3: "4:3",
        annotationCropPreset3x2: "3:2",
        annotationCropPreset16x9: "16:9",
        annotationCropSnap: "Snap to edges",
        annotationCropSnapHelp: "Snap handles to image edges when nearby. Hold ⌘ to disable temporarily.",
        annotationCropWidth: "Crop width in pixels",
        annotationCropHeight: "Crop height in pixels",
        annotationCropErrorInvalid: "Invalid crop area. Adjust the selection and try again.",
        annotationCropRotate: "Rotate 90° clockwise",
        annotationCropFlipHorizontal: "Flip horizontal",
        annotationCropFlipVertical: "Flip vertical",
        annotationCropTransformDisabledHelp: "Rotate and flip are disabled while annotations are present. Remove all annotations first.",
        annotationBeautifyEnabled: "Beautify",
        annotationBeautifyBackground: "Background",
        annotationBeautifyBackgroundSolid: "Solid",
        annotationBeautifyBackgroundBlur: "Blur",
        annotationBeautifySolidColor: "Color",
        annotationBeautifyPadding: "Padding",
        annotationBeautifyCornerRadius: "Radius",
        annotationBeautifyShadow: "Shadow",
        annotationBeautifyShadowIntensity: "Intensity",
        annotationStyleStroke: "Stroke",
        annotationStyleFill: "Fill",
        annotationStyleFillColor: "Fill color",
        annotationStyleLineWidth: "Width",
        annotationStyleLineDash: "Dash",
        annotationStyleFontSize: "Font size",
        annotationTextFill: "Fill",
        annotationTextOutline: "Outline",
        annotationTextTrace: "Trace",
        annotationColorCustom: "Custom color",
        annotationColorEyedropper: "Pick color from screen",
        annotationColorCopyHex: "Copy HEX",
        annotationLineDashSolid: "Solid",
        annotationLineDashDashed: "Dashed",
        annotationLineDashDotted: "Dotted",
        annotationActionCopy: "Copy",
        annotationActionSave: "Save",
        annotationActionPin: "Pin",
        annotationActionDrag: "Drag",
        tipMoveSelection: "Move selection",
        tipScrollCapture: "Long screenshot",
        tipRecord: "Record selection",
        scrollCaptureAutoScroll: "Auto scroll",
        scrollCaptureManualScroll: "Manual scroll",
        scrollCaptureHint: "Scrolling… press any key to finish",
        scrollCaptureManualHint: "Scroll the page, then stop capture",
        autoScrollPermissionNeeded: "Accessibility permission is required for auto scroll.",
        cropLongScreenshotHint: "Drag top/bottom edges to crop the long screenshot",
        mergedLongScreenshot: "Long screenshot ready",
        tipScrollCropConfirm: "Confirm crop",
        annotationZoomIn: "Zoom In",
        annotationZoomOut: "Zoom Out",
        annotationZoomFit: "Fit",
        annotationStatusCopied: "Copied to clipboard.",
        annotationStatusSaved: "Saved.",
        annotationStatusSavedFormat: "Saved to %@",
        annotationStatusPinned: "Pinned to screen.",
        annotationStatusDragReady: "Drag payload ready.",
        annotationErrorNoImage: "No source image is available for export.",
        annotationErrorNoResultMetadata: "Missing screenshot result metadata for copy/save.",
        annotationErrorPinNotWired: "Pin is unavailable.",
        annotationErrorDragNotWired: "Drag is unavailable.",
        annotationErrorRenderFormat: "Render failed: %@",
        annotationErrorPipelineFormat: "Export pipeline failed: %@",
        annotationCloseUnsavedTitle: "Discard annotations?",
        annotationCloseUnsavedMessage: "You have unsaved annotation changes. Closing will discard them.",
        annotationCloseDiscard: "Discard",
        annotationCloseCancel: "Cancel",
        inlineAnnotationFinish: "Done",
        inlineAnnotationCancel: "Cancel",
        inlineAnnotationErrorMissingSelection: "Inline annotation requires a region selection.",
        inlineAnnotationErrorModeNotRegion: "Inline annotation is only available for region captures.",
        inlineAnnotationErrorScreenInvalid: "Inline annotation screen snapshot is invalid.",
        inlineAnnotationErrorEmptyFrame: "Inline annotation could not map a non-empty window frame.",
        inlineAnnotationErrorInvalidImage: "Inline annotation source image is invalid.",
        inlineAnnotationErrorSelectionImageSizeMismatch: "Inline annotation selection pixel size does not match the image.",
        inlineAnnotationErrorPresenterUnavailable: "Inline annotation presenter is not available.",
        allInOneToolbarComplete: "Done",
        allInOneToolbarCopy: "Copy",
        allInOneToolbarOCR: "OCR",
        allInOneToolbarFullscreen: "Fullscreen",
        allInOneToolbarWindow: "Window",
        allInOneToolbarScrolling: "Scroll",
        allInOneToolbarCancel: "Cancel",
        captureAnnotationToolShape: "Shape",
        captureAnnotationToolLine: "Line / Arrow",
        captureAnnotationToolPencil: "Pencil",
        captureAnnotationToolHighlighter: "Highlighter",
        captureAnnotationToolMosaic: "Mosaic",
        captureAnnotationToolText: "Text",
        captureAnnotationToolEraser: "Eraser",
        captureAnnotationActionUndo: "Undo",
        captureAnnotationActionRedo: "Redo",
        captureAnnotationActionCancel: "Cancel",
        captureAnnotationActionPin: "Pin",
        captureAnnotationActionSave: "Save",
        captureAnnotationActionCopy: "Copy",
        captureAnnotationShapeFilledRect: "Filled rectangle",
        captureAnnotationShapeHollowRect: "Hollow rectangle",
        captureAnnotationShapeEllipse: "Ellipse",
        captureAnnotationLineStraight: "Straight line",
        captureAnnotationLineArrow: "Arrow",
        captureAnnotationBrushRound: "Round brush",
        captureAnnotationBrushSquare: "Square brush",
        captureAnnotationMosaicPixelate: "Pixelate",
        captureAnnotationOptionColor: "Color",
        captureAnnotationOptionSize: "Size",
        captureAnnotationOptionMosaicIntensity: "Mosaic intensity",
        captureAnnotationOptionBold: "Bold",
        captureAnnotationOptionItalic: "Italic",
        captureAnnotationOptionFont: "Font",
        captureAnnotationErrorCopy: "Copy failed",
        captureAnnotationErrorSave: "Save failed",
        captureAnnotationErrorPin: "Pin failed",
        captureAnnotationErrorFreeze: "Screen freeze failed",
        // MARK: - Token Usage
        featureHubNameTokenUsage: "Token Usage",
        featureHubDescTokenUsage: "Monitor token usage and limit windows across your AI CLIs",
        controlcenterTabTokenUsage: "Token",
        controlcenterNavTokenUsage: "Token",
        settingsTabTokenUsage: "Token Usage",
        tokenSettingsCaption: "Track token usage and official limit windows across AI CLIs. All data stays on this device.",
        tokenEmptyHint: "No login detected · Run any CLI once to get started",
        tokenReauthHint: "Login expired · Re-login with the CLI to refresh",
        tokenRefresh: "Refresh",
        tokenProviderAll: "All",
        tokenWindowSession5h: "5-hour session window",
        tokenWindowWeekly: "Weekly window",
        tokenWindowMonthly: "Monthly window",
        tokenWindowCredits: "Extra credits",
        tokenWindowCreditsShort: "Credits",
        tokenWindowWeeklyShort: "Week",
        tokenWindowPlanShort: "Plan",
        tokenWindowAutoShort: "Auto",
        tokenStatusNormal: "Normal",
        tokenStatusApproaching: "Approaching limit",
        tokenStatusExceeded: "Limit exceeded",
        tokenStatusReauth: "Re-login required",
        tokenStatusRateLimited: "Rate limited",
        tokenStatusStale: "Stale data",
        tokenErrorNetwork: "Network error",
        tokenErrorTransient: "Temporarily unavailable",
        tokenRateLimitedCaptionFormat: "Rate limited, retry before %@",
        tokenErrorRetryableHint: "retry available",
        tokenBackfilling: "Calculating historical usage…",
        tokenCreditsRemainingFormat: "%@ left",
        tokenResetInApproxFormat: "Resets at %@",
        tokenPaceOver: "Will run out at current pace",
        tokenPaceProjectedFormat: "Projected %d%% at reset",
        tokenCreditCaption: "Auto-refills with billing cycle · Official data",
        tokenResetBankTitle: "Resets",
        tokenResetBankEntryFormat: "Reset %d · expires %@",
        tokenResetBankCountOnlyFormat: "Reset bank: %d · expiry unavailable",
        tokenUpdatedJustNow: "Just updated",
        tokenUpdatedMinutesFormat: "%d min ago",
        tokenUpdatedHoursFormat: "%d h ago",
        tokenSourceOfficial: "Official source",
        tokenFooterFormat: "%@ · %@ · %d configured, %d active",
        tokenUsageLocalFormat: "Local stats · aggregated every %d min",
        tokenSummaryToday: "Today",
        tokenSummarySevenDays: "7 days",
        tokenSummaryThirtyDays: "30 days",
        tokenSummaryTotal: "Total",
        tokenSummaryConversationsFormat: "%d sessions",
        tokenSummaryActiveDaysFormat: "%d active days",
        tokenSummaryAvgPerDayFormat: "~%@/day",
        tokenActivityTitle: "Activity",
        tokenActivityLegendLess: "Less",
        tokenActivityLegendMore: "More",
        tokenTrendTitle: "Trend",
        tokenTrendPeriodDay: "Day",
        tokenTrendPeriodWeek: "Week",
        tokenTrendPeriodMonth: "Month",
        tokenTrendPeriodTotal: "Total",
        tokenTopModelsTitle: "Models",
        tokenUnit: "tokens",
        tokenSettingsGenericSection: "General",
        tokenSettingsProvidersSection: "Providers",
        tokenSettingsAlertsSection: "Alerts",
        tokenSettingsMenuBarMode: "Menu bar display",
        tokenSettingsMenuBarToday: "Today's tokens",
        tokenSettingsMenuBarSession: "Session usage %",
        tokenSettingsMenuBarOff: "Off",
        tokenMenuBarTodayLabel: "Today",
        tokenSettingsRefreshInterval: "Limit refresh interval",
        tokenSettingsRefreshMinuteFormat: "%d min",
        tokenSettingsLimitsDisplay: "Limit display",
        tokenSettingsLimitsUsed: "Used",
        tokenSettingsLimitsRemaining: "Remaining",
        tokenResetToastLabel: "Toast on limit reset",
        tokenResetConfettiLabel: "Confetti on limit reset",
        tokenResetCelebrationFormat: "%@ limit reset 🎉",
        tokenSettingsDefaultPeriod: "Default usage period",
        tokenSettingsProviderStatusFormat: "%@ · %@",
        tokenSettingsLoggedIn: "Signed in",
        tokenSettingsNotConfigured: "Not signed in",
        tokenSettingsHowToConfigure: "How to configure",
        tokenSettingsSessionAlert: "Notify when session usage is 85% or more",
        tokenSettingsPaceAlert: "Notify when running ahead of pace",
        tokenSettingsRequestPermission: "Request notification permission",
        tokenSettingsPermissionGranted: "Authorized",
        tokenSettingsPermissionDenied: "Not authorized",
        tokenSettingsConfigureHintFormat: "Run `%@` once to sign in; it will be detected automatically.",
        tokenSettingsConfigureHintCursor: "Sign in inside the Cursor app; it will be detected automatically.",
        tokenSettingsConfigureHintAntigravity: "Launch Antigravity; usage limits are read while the IDE is running.",
        tokenSettingsConfigureHintTraeCn: "Enter your Trae CN JWT in the settings below; it is stored only in the macOS Keychain.",
        tokenMenuBarSessionLabel: "Session",
        tokenAlertSessionTitle: "Token usage alert",
        tokenAlertSessionBodyFormat: "%@ session usage reached %d%% — consider slowing down.",
        tokenAlertPaceTitle: "Token usage ahead of pace",
        tokenAlertPaceBodyFormat: "%@ session window will run out before it resets at the current pace.",
        tokenDurationDayFormat: "%d d",
        tokenDurationHourFormat: "%d h",
        tokenDurationMinuteFormat: "%d min",
        tokenWeekdayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        deepSeekBalanceCardTitle: "DeepSeek Balance",
        deepSeekBalanceLoading: "Fetching balance…",
        deepSeekBalanceUnavailable: "Balance unavailable",
        deepSeekStatusBelowThreshold: "Below threshold",
        deepSeekStatusReauthKey: "API key invalid",
        deepSeekBalanceFooterFormat: "%@ · %@",
        deepSeekAlertTitle: "DeepSeek balance alert",
        deepSeekAlertBodyFormat: "DeepSeek balance is %@, below the %@ threshold.",
        tokenSettingsDeepSeekSection: "DeepSeek Balance",
        tokenSettingsTraeCnSection: "Trae CN",
        tokenSettingsTraeCnJwtPlaceholder: "Paste your Cloud-IDE-JWT…",
        deepSeekSettingsApiKeySection: "API Key",
        deepSeekSettingsApiKeyPlaceholder: "sk-...",
        deepSeekSettingsSaveKey: "Save",
        deepSeekSettingsClearKey: "Remove",
        deepSeekSettingsKeySaved: "Key saved to Keychain",
        deepSeekSettingsKeyMissing: "No API key",
        deepSeekSettingsApiKeyCaption: "Stored only in your macOS Keychain, never on disk",
        deepSeekSettingsApiKeyInvalid: "Invalid key, check it and try again",
        deepSeekSettingsLowBalanceAlert: "Low balance alert",
        deepSeekSettingsThresholdLabel: "Threshold (¥)",
        deepSeekSettingsThresholdHint: "Notifies once below the threshold; re-arms after balance recovers",
        deepSeekSettingsRefreshInterval: "Balance refresh interval"
    )
}
