import Foundation

extension Strings {
    /// 简体中文翻译
    static let zhHans = Strings(
        appTitle: "OmniForge",
        actionUnlock: "解锁",
        actionLock: "锁定",
        actionQuit: "退出",
        panelSelectSource: "选择要锁定的输入法：",
        settingsLanguage: "语言",
        settingsSystem: "跟随系统",
        settingsLaunchAtLogin: "开机自启",
        settingsHideDockIcon: "隐藏 Dock 图标",
        settingsAccessibility: "辅助功能权限",
        settingsAccessibilityDescription: "需要此权限来拦截输入法切换快捷键",
        settingsGrantAccess: "授予权限",
        settingsDetectedHotkeys: "检测到的输入法切换快捷键",
        settingsNoHotkeysDetected: "未从系统设置中检测到快捷键",
        settingsHotkeysNote: "这些快捷键从系统设置中自动读取。锁定时，按下这些快捷键将被阻止。",
        settingsGeneralSection: "通用",
        settingsClipboardSection: "剪贴板历史",
        settingsClipboardHotkey: "剪贴板快捷键",
        settingsClipboardHotkeyRecording: "按下快捷键...",
        settingsClipboardRetentionDays: "保留",
        settingsClipboardMaxEntries: "上限",
        settingsDays: "天",
        settingsEntries: "条",
        settingsTabGeneral: "通用",
        settingsTabInputMethod: "输入法",
        settingsTabClipboard: "剪贴板",
        settingsTabMonitor: "监控",
        settingsTabMenuBar: "菜单栏",
        settingsTabAlerts: "告警",
        settingsTabPerformance: "性能",
        settingsTabShelf: "暂存架",
        settingsTabScreenshot: "截图",
        settingsTabMouse: "鼠标",
        settingsTitle: "设置",
        clipboardTitle: "剪贴板历史",
        clipboardActionPaste: "粘贴",
        clipboardSearch: "搜索剪贴板...",
        clipboardEmpty: "暂无剪贴板记录",
        clipboardPasteHint: "Paste to",
        clipboardPasteUnknown: "当前应用",
        clipboardSectionToday: "今天",
        clipboardSectionYesterday: "昨天",
        clipboardSectionThisWeek: "本周",
        clipboardSectionLastWeek: "上周",
        clipboardSectionThisMonth: "本月",
        clipboardSectionThisYear: "今年",
        clipboardDetail: "详情",
        clipboardDetailSource: "来源",
        clipboardDetailInformation: "信息",
        clipboardDetailType: "内容类型",
        clipboardDetailDimensions: "尺寸",
        clipboardDetailSize: "图像大小",
        clipboardDetailCharacters: "文本统计",
        clipboardDetailCharactersCount: "字符",
        clipboardDetailWordsCount: "单词",
        clipboardDetailImageUnknown: "未知尺寸",
        clipboardDetailTime: "时间",
        clipboardDetailUnavailable: "无法预览",
        clipboardDetailRtf: "富文本",
        clipboardFilterAll: "全部类型",
        clipboardFilterText: "文本",
        clipboardFilterImage: "图片",
        clipboardFilterFile: "文件",
        clipboardFilterUrl: "链接",
        clipboardFilterRtf: "富文本",
        clipboardFilterUnknown: "未知",
        controlcenterTabDashboard: "主控",
        controlcenterTabSettings: "设置",
        controlcenterTabAccessibility: "控制中心页面切换",
        controlcenterTabSystemMonitor: "系统监控",
        controlcenterInputLockDescription: "锁定后将持续保持所选输入法",
        controlcenterInputLockNoSource: "当前没有可锁定的输入法",
        controlcenterClipboardTitle: "剪贴板历史",
        controlcenterClipboardEnabled: "已开启，支持快捷键唤起",
        controlcenterClipboardDisabled: "已关闭，快捷键不会触发",
        controlcenterOpenSettings: "设置",
        controlcenterTabUtilities: "实用工具",
        controlcenterNavMonitor: "监控",
        controlcenterNavKeepAwake: "唤醒",
        controlcenterNavUtilities: "工具",
        controlcenterEmpty: "控制中心没有可显示的已安装模块。",
        runStateStopped: "已停止",
        runStateRunning: "运行中",
        runStateEnabled: "已开启",
        runStateWaitingPermission: "等待权限",
        runStateFailed: "运行异常：%@",
        actionRetry: "重试",
        permissionOpenSettings: "打开系统设置",
        utilityCleaner: "清理",
        utilityUninstaller: "卸载器",
        utilityUninstallBusy: "操作完成后可卸载",
        utilityCleanerSubtitle: "清理残留、缓存、日志与废纸篓",
        utilityUninstallerSubtitle: "彻底卸载应用及其关联文件",
        utilityColorPickerSubtitle: "从屏幕拾取颜色并复制色值",
        utilityNetworkDiagnosticsSubtitle: "查看本机网络身份与端口占用",
        utilityDSHWebSubtitle: "启动、停止与重启 dsh web 服务",
        toolRetryFailures: "重试失败项",
        toolSucceeded: "成功项",
        toolFailed: "失败项",
        toolScanFailure: "无法扫描 %@：%@",
        monitorSettingsTitle: "监控",
        monitorSettingsEnable: "启用监控",
        monitorSettingsRefreshInterval: "刷新间隔",
        monitorSettingsTemperatureUnit: "温度单位",
        monitorSettingsCelsius: "摄氏度",
        monitorSettingsFahrenheit: "华氏度",
        monitorPanelSectionsTitle: "面板分区",
        monitorSectionSystem: "系统",
        monitorSectionNetwork: "网络",
        monitorSectionDisk: "磁盘",
        monitorSectionPower: "电源",
        settingsMoveUp: "↑",
        settingsMoveDown: "↓",
        monitorMetricCpu: "CPU",
        monitorMetricGpu: "GPU",
        monitorMetricMemory: "内存",
        monitorMetricCpuTemp: "CPU 温度",
        monitorMetricGpuTemp: "GPU 温度",
        monitorMetricDown: "下载",
        monitorMetricUp: "上传",
        monitorMetricTotalDown: "累计下载",
        monitorMetricTotalUp: "累计上传",
        monitorMetricRead: "读取",
        monitorMetricWrite: "写入",
        monitorMetricFree: "可用",
        monitorMetricBattery: "电池",
        monitorMetricCharging: "充电中",
        monitorValueYes: "是",
        monitorValueNo: "否",
        monitorMetricHealth: "健康度",
        monitorMetricCycles: "循环次数",
        monitorMetricRemaining: "剩余",
        monitorMetricSystemPower: "系统功耗",
        monitorMetricBatteryPower: "电池功率",
        monitorIssueUnsupported: "不支持",
        monitorIssueFailed: "失败",
        monitorNoDiskData: "无磁盘数据",
        monitorNoPowerData: "无电源数据",
        monitorProcessLoading: "正在加载%@…",
        monitorProcessUsage: "%@ 占用",
        monitorProcessEmpty: "暂无进程数据",
        monitorSpeedTestStart: "开始测速",
        monitorSpeedTestRunning: "测速中…",
        monitorSpeedTestFailed: "测速失败",
        monitorDeviceFallbackName: "Mac",
        monitorStatusNormal: "正常",
        monitorStatusIssue: "异常",
        monitorPreferences: "偏好设置",
        monitorRefreshAll: "全部刷新",
        monitorCardStorage: "存储",
        monitorCardDisk: "磁盘",
        monitorCardNetworkTraffic: "网络",
        monitorCardDiskIO: "磁盘 I/O",
        monitorCardEnergy: "能耗",
        monitorLiveBadge: "实时",
        monitorProcessNameHeader: "进程名",
        monitorProcessShareHeader: "占比",
        monitorRankingTitleCPU: "CPU 占用",
        monitorRankingTitleGPU: "GPU 占用",
        monitorRankingTitleMemory: "内存占用",
        monitorRankingTitleNetwork: "网络占用",
        monitorRankingTitleEnergy: "能耗占用",
        monitorFreeLabel: "可用",
        monitorOfTotal: "共 %@",
        monitorSubtitleSeparator: "•",
        monitorPressureNormal: "正常",
        monitorPressureWarning: "警告",
        monitorPressureCritical: "危急",
        monitorCPUSystem: "系统",
        monitorCPUUser: "用户",
        monitorUptimePrefix: "已运行",
        monitorPowerSourceAdapter: "电源适配器",
        monitorPowerSourceOnBattery: "使用电池",
        monitorDiskUsed: "已用",
        monitorCumulativeTotal: "累计",
        monitorMetricHealthShort: "健康",
        // 磁盘详情
        diskSectionTitle: "磁盘",
        diskSelect: "选择磁盘",
        diskUsed: "已用",
        diskFree: "可用",
        diskInternal: "内置",
        diskExternal: "外置",
        diskRead: "读取",
        diskWrite: "写入",
        diskThisSession: "本次会话",
        diskMeasuring: "测量中",
        diskSMART: "SMART",
        diskSMARTStatus: "状态",
        diskTotalWritten: "总写入",
        diskTotalRead: "总读取",
        diskTemperature: "温度",
        diskHealth: "健康度",
        diskPowerCycles: "通电次数",
        diskPowerOnHours: "通电小时",
        diskSMARTUnavailable: "此磁盘没有可用的 SMART",
        diskUnsupported: "不支持",
        diskProtection: "外置保护",
        diskEject: "推出",
        diskEjectAll: "全部推出",
        diskEjecting: "正在推出…",
        diskReadyToRemove: "可以移除",
        diskEjectFailed: "无法推出",
        diskNoExternal: "没有可推出的外置磁盘。",
        diskProtectionCaption: "拔出前先推出。",
        diskTools: "工具",
        diskOpenInFinder: "打开",
        diskStorageSettings: "存储",
        diskUsage: "磁盘使用",
        diskActivity: "实时活动",
        diskNoDisks: "未找到已挂载磁盘",
        diskFileSystemUnsupported: "不支持",
        menubarSettingsEnable: "在菜单栏显示指标",
        menubarSettingsTitle: "菜单栏指标",
        menubarSettingsPreview: "预览",
        menubarSettingsSpacing: "间距",
        menubarSettingsCompact: "紧凑",
        menubarSettingsStandard: "标准",
        menubarSettingsMemoryStyle: "内存样式",
        menubarSettingsMemoryPercent: "百分比",
        menubarSettingsMemoryUsed: "已用",
        menubarSettingsMemoryPressure: "压力",
        menubarSettingsNetworkUploadFirst: "上传优先显示",
        menubarSettingsCombineTemperatures: "合并温度显示",
        menubarSettingsSeparateStatusItems: "独立状态项",
        menubarSettingsHideMainIcon: "有指标时隐藏主图标",
        menubarMetricCPU: "CPU",
        menubarMetricGPU: "GPU",
        menubarMetricMemory: "内存",
        menubarMetricNetwork: "网络",
        menubarMetricDisk: "磁盘",
        menubarMetricPower: "电源",
        menubarMetricBattery: "电池",
        menubarMetricCPUTemperature: "CPU 温度",
        menubarMetricGPUTemperature: "GPU 温度",
        menubarMetricBatteryTemperature: "电池温度",
        menubarMetricPeripheralBattery: "外设电池",
        menubarMetricDate: "日期",
        settingsInputMethodSection: "输入法",
        alertsSettingsTitle: "告警",
        alertsCpu: "CPU 告警",
        alertsCpuTemperature: "CPU 温度告警",
        alertsMemory: "内存告警",
        alertsDisk: "磁盘告警",
        alertsBattery: "电池告警",
        alertsNotificationTitle: "监控告警",
        alertsBodyCpu: "CPU 使用率超过 %d%%",
        alertsBodyCpuTemperature: "CPU 温度超过 %d°",
        alertsBodyMemory: "内存压力过高",
        alertsBodyDisk: "磁盘剩余空间低于 %d%%",
        alertsBodyBattery: "电池电量低于 %d%%",
        quickphraseSearchPlaceholder: "搜索快捷用语...",
        menuAbout: "关于 OmniForge",
        menuSettings: "设置…",
        menuHide: "隐藏",
        menuHideOthers: "隐藏其他",
        menuShowAll: "全部显示",
        menuQuit: "退出 OmniForge",
        menuEdit: "编辑",
        menuUndo: "撤销",
        menuRedo: "重做",
        menuCut: "剪切",
        menuCopy: "拷贝",
        menuPaste: "粘贴",
        menuSelectAll: "全选",
        menuWindow: "窗口",
        menuMinimize: "最小化",
        menuZoom: "缩放",
        menuClose: "关闭",
        // Feature Hub
        settingsTabFeatures: "特性",
        settingsFeatureEnabled: "已开启",
        settingsFeatureDisabled: "已关闭",
        featureHubIntro: "卸载立即释放运行时；磁盘数据保留，可随时重装。",
        featureHubTabFeatures: "特性",
        featureHubTabPermissions: "权限",
        featureHubActiveCount: "已安装 %d / %d",
        featureHubInstallAll: "全部安装",
        featureHubUninstallAll: "全部卸载",
        featureHubInstall: "安装",
        featureHubUninstall: "卸载",
        featureHubRestartNote: "本会话有特性未能完全释放。重启以完成卸载。",
        featureHubRestartButton: "立即重启",
        featureHubNameInputLock: "输入法锁定",
        featureHubNameClipboardHistory: "剪贴板历史",
        featureHubNameQuickPhrase: "快捷短语",
        featureHubNameSystemMonitor: "系统监控",
        featureHubNameNetworkDiagnostics: "网络诊断",
        featureHubNameShelf: "暂存架",
        featureHubNameLaunchAtLogin: "开机自启",
        featureHubNameScrollInverter: "反转滚动",
        featureHubNameSmoothScroll: "平滑滚动",
        featureHubNameMouseNavigation: "鼠标导航",
        featureHubNameDockClick: "Dock 点击",
        featureHubNameKeepAwake: "保持唤醒",
        featureHubNameScreenshot: "截图",
        featureHubNameDSHWeb: "DSH Web 服务",
        featureHubDescInputLock: "锁定输入法，打字时保持不变。",
        featureHubDescClipboardHistory: "在本地保存复制记录以供复用。",
        featureHubDescQuickPhrase: "存储并粘贴常用文本片段。",
        featureHubDescSystemMonitor: "在菜单栏中跟踪 CPU、内存、磁盘和电池。",
        featureHubDescNetworkDiagnostics: "按需查看本机网络身份与端口占用。",
        featureHubDescShelf: "一个浮动空间，用来收集文件、图像和文本，稍后再拖到任何 App 中。",
        featureHubDescLaunchAtLogin: "登录时自动启动 OmniForge。",
        featureHubDescScrollInverter: "反转鼠标滚轮方向，同时保持触控板的自然滚动。",
        featureHubDescSmoothScroll: "把鼠标滚轮的离散刻度变为顺滑的滑行。",
        featureHubDescMouseNavigation: "把鼠标侧键映射为后退和前进。",
        featureHubDescDockClick: "任务栏式 Dock 点击，最小化、恢复和循环窗口。",
        featureHubDescKeepAwake: "阻止系统与显示器睡眠，支持定时会话、低电量保护和可选合盖运行。",
        featureHubDescScreenshot: "截取屏幕、标注、OCR、钉图，并在菜单栏统一管理钉图。",
        featureHubDescDSHWeb: "启动、停止与重启 dsh web 服务",
        featureHubGroupInput: "输入",
        featureHubGroupClipboard: "剪贴板与短语",
        featureHubGroupMonitor: "系统监控",
        featureHubGroupProductivity: "生产力",
        featureHubGroupSystem: "系统",
        featureHubGroupMouse: "鼠标与触控板",
        featureHubGroupEnergy: "电源与唤醒",
        featureHubGroupCapture: "截图与捕获",
        featureHubPermissionsIntro: "查看每个权限的用途，以及哪些特性需要它。",
        featureHubPermStatusGranted: "已授予",
        featureHubPermStatusMissing: "未授予",
        featureHubPermUsedBy: "使用方",
        featureHubPermUsedByNone: "没有已安装的特性需要此权限。",
        featureHubPermUsageRequired: "必需",
        featureHubPermUsageConfigured: "已配置",
        featureHubPermUsageOptional: "可选",
        featureHubPermUsageInactive: "当前未使用",
        featureHubPermOpenSettings: "打开系统设置",
        featureHubPermRefresh: "重新检测",
        featureHubPermRecoveryHint: "若权限已开启但未生效，请退出 OmniForge 后重新开启权限，或移除并重新添加当前安装版。",
        featureHubPermSignature: "当前签名",
        featureHubPermNameAccessibility: "辅助功能",
        featureHubPermNameInputMonitoring: "输入监控",
        featureHubPermNameNotifications: "通知",
        featureHubPermDescAccessibility: "允许 OmniForge 拦截输入法切换快捷键。",
        featureHubPermDescInputMonitoring: "允许 OmniForge 读取键盘事件以检测快捷键。",
        featureHubPermDescNotifications: "允许系统监控向你发送提醒。",
        featureHubPermNameFullDiskAccess: "完全磁盘访问",
        featureHubPermDescFullDiskAccess: "允许卸载器和清理器扫描受保护位置中的遗留和垃圾文件。",
        featureHubPermNameScreenRecording: "屏幕录制",
        featureHubPermDescScreenRecording: "允许 OmniForge 捕获屏幕以进行截图、标注与区域录屏。",
        // Onboarding
        onboardingWelcomeTitle: "欢迎使用 OmniForge",
        onboardingWelcomeBody: "锁定输入法、管理剪贴板历史、快捷短语和系统监控，一切尽在菜单栏。",
        onboardingNext: "下一步",
        onboardingBack: "上一步",
        onboardingFinish: "完成",
        onboardingSkip: "跳过",
        onboardingPermissionsTitle: "权限设置",
        onboardingPermissionsBody: "OmniForge 需要以下权限才能正常工作。您可以稍后在系统设置中修改。",
        onboardingPermissionAccessibility: "辅助功能",
        onboardingPermissionAccessibilityDescription: "拦截输入法切换快捷键所必需",
        onboardingPermissionNotifications: "通知",
        onboardingPermissionNotificationsDescription: "系统监控警报和重要提醒所必需",
        onboardingGrantPermission: "授予权限",
        onboardingPermissionGranted: "已授权",
        onboardingRecheck: "重新检查",
        onboardingPermissionHint: "授权后如果应用重启，向导将从当前步骤继续。",
        onboardingFeaturesTitle: "功能概览",
        onboardingFeaturesBody: "以下是 OmniForge 提供的所有功能。您可以在设置中随时启用或禁用。",
        onboardingFeatureInputLockTitle: "输入法锁定",
        onboardingFeatureInputLockDescription: "锁定当前输入法，防止意外切换",
        onboardingFeatureClipboardHistoryTitle: "剪贴板历史",
        onboardingFeatureClipboardHistoryDescription: "自动记录剪贴板内容，支持搜索和粘贴",
        onboardingFeatureQuickPhraseTitle: "快捷短语",
        onboardingFeatureQuickPhraseDescription: "保存常用短语，快速插入到任意应用",
        onboardingFeatureSystemMonitorTitle: "系统监控",
        onboardingFeatureSystemMonitorDescription: "实时监控 CPU、内存、磁盘和网络状态",
        onboardingFeatureShelfTitle: "暂存架",
        onboardingFeatureShelfDescription: "一个浮动空间，用来收集文件、图像和文本，稍后再拖到任何 App 中",
        onboardingFeatureLaunchAtLoginTitle: "开机自启",
        onboardingFeatureLaunchAtLoginDescription: "登录时自动启动 OmniForge",
        onboardingDoneTitle: "设置完成",
        onboardingDoneHint: "点击菜单栏图标开始使用 OmniForge。您可以在设置中随时修改配置。",
        // What's New
        whatsNewTitle: "更新内容",
        whatsNewClose: "关闭",
        // Shelf
        shelfName: "暂存架",
        shelfEnable: "用于拖放文件的临时区域",
        shelfEnableCaption: "一个浮动空间，用来收集文件、图像和文本，稍后再拖到任何 App 中。",
        shelfHowTitle: "使用方法",
        shelfStep1: "用快捷键打开它，或在拖动时晃动鼠标打开。",
        shelfStep2: "把文件、图像、链接或文本拖放到上面以暂存。",
        shelfStep3: "需要时再把每个项目拖回任何 App。",
        shelfShakeToggle: "拖动时晃动鼠标打开",
        shelfShakeCaption: "按住某个项目时快速晃动指针，即可在光标附近呼出暂存架。",
        shelfDropZoneToggle: "将拖动的文件保留在菜单栏",
        shelfDropZoneCaption: "拖动文件时，暂存架会出现在菜单栏图标下方。放下的内容就保存在那里，收进一个点按即可收起或打开的按钮，暂存架清空后按钮会消失。",
        shelfDropZoneLabel: "放到这里",
        shelfCollapse: "收起",
        shelfBehaviorTitle: "使用后",
        shelfCloseAfterDrop: "拖放到其他 App 后关闭",
        shelfCloseAfterDropCaption: "目标接收项目后关闭暂存架。面板中的图钉可让它保持打开。",
        shelfRemoveAfterDrop: "拖放后移除项目",
        shelfRemoveAfterDropCaption: "其他 App 接收的项目会离开暂存架。关闭此项可保留副本。",
        shelfExclusionsTitle: "自动例外",
        shelfExclusionsEmpty: "尚未添加 App。",
        shelfExclusionsCaption: "从这些 App 开始拖移时，摇动手势和菜单栏区域不会打开。快捷键和立即打开仍可使用。",
        shelfPin: "保持打开",
        shelfUnpin: "允许使用后关闭",
        shelfHotkeyLabel: "快捷键",
        shelfOpenNow: "立即打开",
        shelfNoPermission: "无需任何权限。",
        shelfMenuItem: "打开暂存架",
        shelfTitle: "暂存架",
        shelfEmpty: "将项目拖到这里",
        shelfClearAll: "全部清除",
        shelfRemoveSelected: "移除所选",
        shelfSelectedFormat: "已选择 %d 项",
        shelfHint: "点按以选择，拖出即可使用，或右键点按查看更多操作。",
        shelfItemImage: "图像",
        shelfActionOpen: "打开",
        shelfActionOpenWith: "打开方式",
        shelfActionAirDrop: "通过 AirDrop 共享",
        shelfActionReveal: "在 Finder 中显示",
        shelfShortcutToggle: "暂存架快捷键",
        shelfFeatureUnavailable: "请先在「功能」中安装暂存架后再使用这些设置。",
        shelfAddApp: "添加 App…",
        shelfAppPickerTitle: "选择 App",
        shelfAppPickerSearch: "搜索",
        shelfAppPickerCancel: "取消",
        shelfAppPickerEmpty: "未找到 App。",
        // Uninstaller
        uninstallerName: "卸载器",
        uninstallerEnableCaption: "在移除 App 的同时，清除它遗留的缓存、偏好设置、日志和残留文件。",
        uninstallerDropTitle: "将 App 拖到这里",
        uninstallerDropSubtitle: "或选择一个进行扫描",
        uninstallerChoose: "选择 App…",
        uninstallerPickerTitle: "选择 App",
        uninstallerPickerSearch: "搜索 App",
        uninstallerPickerEmpty: "未找到 App",
        uninstallerEmptyNote: "未经你确认，不会移除任何内容。",
        uninstallerFDANote: "授予完全磁盘访问权限可进行更彻底的扫描。",
        uninstallerFDAGrant: "授予访问权限…",
        uninstallerFDAHint: "在列表中开启 OmniForge。如果列表中没有，点按 + 并从“应用程序”中选择 OmniForge。访问权限须在你重新打开 App 后才会生效。",
        uninstallerFDARelaunch: "立即重新打开",
        uninstallerScanning: "正在扫描文件…",
        uninstallerRemoving: "正在移到废纸篓…",
        uninstallerFoundTitle: "已找到",
        uninstallerSelectedFormat: "已选择 %d 项，共 %d 项",
        uninstallerRemove: "移到废纸篓",
        uninstallerCancel: "取消",
        uninstallerDoneTitle: "完成！",
        uninstallerFreedFormat: "已释放 %@",
        uninstallerSomeFailed: "部分项目无法移到废纸篓。",
        uninstallerAnother: "卸载另一个",
        uninstallerCatApp: "应用程序",
        uninstallerCatSupport: "支持文件",
        uninstallerCatCaches: "缓存",
        uninstallerCatPreferences: "偏好设置",
        uninstallerCatContainers: "容器",
        uninstallerCatLogs: "日志",
        uninstallerCatState: "已存储状态",
        uninstallerCatOther: "其他",
        // Color Picker
        colorPickerName: "取色器",
        colorPickerDescription: "从屏幕任意位置拾取颜色，支持 HEX / RGB / HSL。",
        colorPickerIntroTitle: "拾取屏幕颜色",
        colorPickerIntroCaption: "点击下方按钮，移动放大镜到任意位置后点击确认。按 ESC 取消。",
        colorPickerStart: "开始取色",
        colorPickerInProgress: "请在屏幕上点选颜色…",
        colorPickerPickAgain: "再次取色",
        colorPickerFormatHex: "HEX",
        colorPickerFormatRGB: "RGB",
        colorPickerFormatHSL: "HSL",
        // Network Diagnostics
        networkDiagnosticsSegmentNetwork: "网络",
        networkDiagnosticsSegmentPorts: "端口",
        networkDiagnosticsRefresh: "刷新",
        networkDiagnosticsCopy: "复制",
        networkDiagnosticsValueUnavailable: "—",
        networkDiagnosticsHostSection: "主机",
        networkDiagnosticsHostname: "主机名",
        networkDiagnosticsInterfacesSection: "网卡",
        networkDiagnosticsInterfaceIPv4: "IPv4",
        networkDiagnosticsInterfaceIPv6: "IPv6",
        networkDiagnosticsInterfaceMAC: "MAC",
        networkDiagnosticsRouteSection: "默认路由",
        networkDiagnosticsGateway: "网关",
        networkDiagnosticsRouteInterface: "接口",
        networkDiagnosticsDNSSection: "DNS",
        networkDiagnosticsDNSServers: "DNS 服务器",
        networkDiagnosticsPublicIPSection: "公网 IP",
        networkDiagnosticsPublicIPv4: "公网 IPv4",
        networkDiagnosticsPublicIPv6: "公网 IPv6",
        networkDiagnosticsPublicIPLoading: "正在查询…",
        networkDiagnosticsNetworkEmpty: "暂无网络信息",
        networkDiagnosticsNetworkLoadFailed: "网络信息加载失败",
        networkDiagnosticsSearchPlaceholder: "搜索端口 / 进程名…",
        networkDiagnosticsScopeListen: "LISTEN",
        networkDiagnosticsScopeAll: "全部",
        networkDiagnosticsColumnProtocol: "协议",
        networkDiagnosticsColumnLocalPort: "本地端口",
        networkDiagnosticsColumnProcess: "进程(PID)",
        networkDiagnosticsColumnStatus: "状态",
        networkDiagnosticsPortsEmpty: "暂无连接",
        networkDiagnosticsPortsEmptyListen: "暂无监听端口",
        networkDiagnosticsPortsLoadFailed: "端口信息采集失败",
        networkDiagnosticsPortsLoadFailedBanner: "采集失败，可复制终端命令自取",
        networkDiagnosticsPartialPermissionBanner: "部分信息需更高权限才能显示",
        networkDiagnosticsCopyTerminalCommand: "复制终端命令",
        networkDiagnosticsShowCommand: "查看命令",
        networkDiagnosticsHideCommand: "收起命令",
        networkDiagnosticsCopyHostPort: "复制 host:port",
        networkDiagnosticsCopyPID: "复制 PID",
        networkDiagnosticsCopyProcessName: "复制进程名",
        networkDiagnosticsCopySudoKill: "复制 sudo kill 命令",
        networkDiagnosticsCopySudoKill9: "复制 sudo kill -9 命令",
        networkDiagnosticsTerminateProcess: "结束进程",
        networkDiagnosticsTerminateTitle: "结束进程？",
        networkDiagnosticsTerminateMessageFormat: "将向 %@（PID %d，端口 %d）发送终止信号（SIGTERM）。",
        networkDiagnosticsTerminateConfirm: "结束",
        networkDiagnosticsTerminateCancel: "取消",
        networkDiagnosticsTerminateSuccess: "已发送终止信号",
        networkDiagnosticsAlertOK: "好",
        networkDiagnosticsProcessGone: "进程已不存在",
        networkDiagnosticsForceTerminateTitle: "强制结束？",
        networkDiagnosticsForceTerminateMessage: "SIGTERM 未能结束该进程，是否发送 SIGKILL？",
        networkDiagnosticsForceTerminateConfirm: "强制结束",
        networkDiagnosticsTerminateFailed: "无法结束进程，可复制 sudo 命令在终端执行",
        networkDiagnosticsProtectedProcess: "系统关键进程不可结束",
        networkDiagnosticsUnknownProcess: "未知进程",
        dshWebStart: "启动",
        dshWebStop: "停止",
        dshWebRestart: "重启",
        dshWebOpenBrowser: "在浏览器打开",
        dshWebStateRunning: "运行中",
        dshWebStateStopped: "已停止",
        dshWebStateStarting: "启动中…",
        dshWebStateStopping: "停止中…",
        dshWebStateFailed: "失败：%@",
        dshWebPortOccupied: "端口 3080 已被占用，可能已有 dsh web 或其它服务在运行",
        dshWebPortOccupiedFormat: "端口 %d 已被占用，可能已有 dsh web 或其它服务在运行",
        dshWebStartTimeout: "启动超时，服务未就绪",
        dshWebLaunchFailed: "无法启动 dsh web 进程",
        dshWebLogTitle: "运行日志",
        dshWebLogEmpty: "暂无日志",
        dshWebCopyLog: "复制",
        dshWebClearLog: "清空",
        dshWebPort: "端口",
        dshWebRefresh: "刷新",
        dshWebServicesTitle: "已发现的服务",
        dshWebExternalServicesTitle: "已发现的外部服务",
        dshWebNoServices: "未发现正在运行的 DSH Web 服务",
        dshWebManagedService: "由本应用启动",
        dshWebExternalService: "外部启动",
        dshWebStopExternalTitle: "停止外部 DSH Web 服务？",
        dshWebStopExternalMessageFormat: "将停止 PID %d（端口 %d）处由外部启动的 DSH Web 服务。",
        dshWebCancel: "取消",
        networkDiagnosticsProcessPIDFormat: "%@ (%d)",
        // Cleaner
        cleanerName: "清理",
        cleanerIntroTitle: "清理 Mac 垃圾",
        cleanerIntroCaption: "查找已卸载 App 的残留、缓存、日志和废纸篓。清理前可逐项确认，移除的项目会进入废纸篓。",
        cleanerScan: "扫描",
        cleanerScanning: "正在扫描…",
        cleanerScanProgressFormat: "已检查 %d 个候选 · 发现 %d 项 · %@",
        cleanerCleaning: "正在清理…",
        cleanerCatLeftovers: "已卸载 App 的残留",
        cleanerCatLoginItems: "失效的登录项",
        cleanerCatCaches: "缓存",
        cleanerCatLogs: "日志",
        cleanerCatDeveloper: "开发垃圾",
        cleanerCatTrash: "废纸篓",
        cleanerLeftoversNote: "由分析找到，默认不勾选。勾选前请确认路径。",
        cleanerLoginItemsNote: "登录项里的条目在 Mac 重新启动后消失。",
        cleanerTrashNote: "清倒废纸篓是永久操作。",
        cleanerCatDeviceBackups: "iPhone 备份",
        cleanerDeviceBackupsCaption: "旧的 iPhone 和 iPad 备份占据了 macOS 所称“其他”存储的很大一部分。只删除不再需要的备份；下次连接设备时会生成新的备份。",
        cleanerNothingFound: "没有可清理的内容。Mac 很整洁。",
        cleanerClean: "清理",
        cleanerDoneNote: "项目已移到废纸篓，可以从那里恢复。",
        cleanerAgain: "再次扫描",
        cleanerRevealInFinder: "在访达中显示",
        cleanerSafeSection: "安全清理",
        cleanerOptionalSection: "可选，请先确认",
        cleanerCatOtherCaches: "其他缓存",
        cleanerCachesCaption: "App 会自行重建的临时文件。",
        cleanerLogsCaption: "旧的诊断日志。",
        cleanerDeveloperCaption: "Xcode 构建和模拟器残留。",
        cleanerLoginItemsCaption: "已不存在的 App 留下的登录项。",
        cleanerLeftoversCaption: "已卸载 App 留下的文件。",
        cleanerOtherCachesCaption: "可以放心删除，不会损坏任何东西。App 首次打开可能变慢，离线音乐等已下载内容会重新下载。",
        cleanerCleanSizeFormat: "清理 %@",
        cleanerScheduleTitle: "自动清理",
        cleanerScheduleOff: "关闭",
        cleanerScheduleDaily: "每天",
        cleanerScheduleWeekly: "每周",
        cleanerScheduleCaption: "在所选时间自动清理安全部分，并把所有内容移到废纸篓。",
        cleanerScheduleLastFormat: "上次自动清理释放了 %@。",
        cleanerAutoNotificationFormat: "已释放 %@ 并移到废纸篓。",
        cleanerScheduleNextFormat: "下次清理%@。",
        cleanerScheduleRanFormat: "上次自动清理%@。",
        cleanerScheduleNotifyToggle: "完成时通知",
        cleanerNotifDenied: "OmniForge 的通知在系统中已关闭。",
        cleanerNotifOpenSettings: "打开通知设置…",

        // MARK: - Mouse & Trackpad
        scrollSection: "滚动",
        invertMouseScroll: "反转鼠标滚轮方向",
        invertMouseScrollCaption: "鼠标滚轮反向滚动，如同旧版 macOS。触控板保持自然滚动。",
        scrollTrackpadNote: "只影响真实的鼠标滚轮；触控板、Magic Mouse 和惯性滚动原样透传。",
        scrollActiveNow: "正在反转",
        smoothScrollName: "平滑滚动",
        smoothScrollCaption: "把鼠标滚轮的离散刻度变为顺滑的滑行。",
        smoothScrollStepLabel: "每刻度像素",
        mouseNavigationSection: "侧键",
        mouseNavigationEnable: "用侧键执行后退和前进",
        mouseNavigationCaption: "Back 和 Forward 侧键触发对应的应用命令（如 Finder 和浏览器的导航）。",
        mouseNavigationActiveNow: "已激活",
        dockClickSection: "程序坞",
        dockClickMinimize: "点击前台 App 的 Dock 图标以最小化",
        dockClickMinimizeCaption: "点击前台 App 的 Dock 图标会最小化其窗口，如同任务栏。",
        dockClickCycleWindows: "点击前台 App 的 Dock 图标以循环窗口",
        dockClickCycleWindowsCaption: "当 App 有多个窗口时，每次点击其 Dock 图标会依次把下一个窗口提到最前。",
        permissionRequired: "所需权限",
        keepAwakeTitle: "保持唤醒",
        keepAwakeDurationLabel: "唤醒时长",
        keepAwakeDurationNever: "永不",
        keepAwakeDuration15m: "15 分钟",
        keepAwakeDuration1h: "1 小时",
        keepAwakeDuration4h: "4 小时",
        keepAwakeClamshellTitle: "合盖时保持唤醒",
        keepAwakeClamshellSubtitle: "需连接电源适配器",
        keepAwakeClamshellFootnote: "开启后，合上盖子时屏幕将保持运行",
        keepAwakeStatusCurrentPrefix: "当前: %@",
        keepAwakeOptionsSection: "选项",
        keepAwakeRemainingLabel: "剩余",
        keepAwakeEndsAtLabel: "关闭时刻",
        keepAwakeOpenSettingsHint: "打开保持唤醒设置以配置授权",
        keepAwakeClamshellCaption: "首次可能需要输入一次管理员密码",
        keepAwakeStart: "开启",
        keepAwakeStop: "关闭",
        keepAwakeRetryCleanup: "重试清理",
        keepAwakeUnavailable: "不可用",
        keepAwakeStatusFeatureUnavailable: "功能未安装",
        keepAwakeStatusWaitingRecovery: "等待合盖恢复完成",
        keepAwakeStatusNormalSleep: "正常睡眠",
        keepAwakeStatusNotActiveWithError: "未开启 — %@",
        keepAwakeStatusStarting: "正在开启…",
        keepAwakeStatusActiveTimed: "已开启，按计划结束",
        keepAwakeStatusActiveIndefinite: "已开启，无限期",
        keepAwakeStatusStopping: "正在关闭…",
        keepAwakeStatusCleanupRequired: "需要清理 — 系统睡眠可能未恢复",
        keepAwakeClamshellChecking: "合盖：检查中",
        keepAwakeClamshellAuthorizing: "合盖：授权中",
        keepAwakeClamshellEnabling: "合盖：启用中",
        keepAwakeClamshellActive: "合盖：已启用",
        keepAwakeClamshellRestoring: "合盖：恢复中",
        keepAwakeClamshellConflict: "合盖：冲突",
        keepAwakeClamshellFailed: "合盖：失败",
        keepAwakeRecoveryCheckingTitle: "正在检查合盖恢复",
        keepAwakeRecoveryCheckingDetail: "正在验证 SleepDisabled 与恢复记录…",
        keepAwakeRecoveryRestoringTitle: "正在恢复系统睡眠",
        keepAwakeRecoveryRestoringDetail: "正在执行受限 pmset 恢复…",
        keepAwakeRecoveryCleanupTitle: "需要清理合盖状态",
        keepAwakeRecoveryConflictTitle: "合盖恢复冲突",
        keepAwakeRetry: "重试",
        keepAwakeMenuStartDefault: "按默认时长开启",
        keepAwakeMenuRetryLastStart: "重试上次开启",
        keepAwakeMenuStartDuration: "开启时长",
        keepAwakeMenuProcessing: "处理中…",
        keepAwakeMenuStop: "关闭保持唤醒",
            keepAwakeMenuRetryCleanup: "重试清理",
            keepAwakeMenuOpenSettings: "打开保持唤醒设置",
            keepAwakeClamshellAction: "合盖保持唤醒",
            keepAwakeMenuQuit: "退出 OmniForge",
        keepAwakeTooltipInactive: "正常睡眠",
        keepAwakeTooltipInactiveWithError: "保持唤醒未开启 — %@",
        keepAwakeTooltipActivating: "正在开启保持唤醒",
        keepAwakeTooltipDeactivating: "正在关闭保持唤醒",
        keepAwakeTooltipActiveTimed: "保持唤醒至 %@",
        keepAwakeTooltipActiveIndefinite: "保持唤醒（无限期）",
        keepAwakeTooltipCleanupRequired: "需要清理",
        keepAwakeNotificationTitle: "保持唤醒",
        keepAwakeAuthDisclosureTitle: "配置合盖授权",
        keepAwakeAuthDisclosureBody: "授权会为当前用户安装仅允许两条精确 pmset 命令的 sudoers 规则（NOPASSWD）。同用户其他进程也可执行这两条命令。pmset disablesleep 属于未公开接口，兼容性不保证。异常退出后的恢复边界是「下次启动 OmniForge 时恢复」，不是崩溃后立即恢复。卸载 Feature 不会自动删除规则。",
        keepAwakeAuthContinue: "继续并输入管理员密码",
        keepAwakeAuthRemoveTitle: "移除合盖授权",
        keepAwakeAuthRemoveBody: "将删除当前用户的受限 sudoers 规则。移除前必须已恢复系统睡眠（SleepDisabled=0）。",
        keepAwakeAuthRemove: "移除",
        keepAwakeAuthCancel: "取消",
        keepAwakeSectionSession: "会话",
        keepAwakeDefaultDuration: "默认时长",
        keepAwakeDurationIndefinite: "无限期",
        keepAwakeDurationMinutesFormat: "%d 分钟",
        keepAwakeDurationHoursFormat: "%d 小时",
        keepAwakeAutoStart: "启动时自动开启",
        keepAwakeSectionBattery: "电量保护",
        keepAwakeBatteryThreshold: "低电量阈值",
        keepAwakeBatteryOff: "关闭",
        keepAwakeBatteryPercentFormat: "%d%%",
        keepAwakeBatteryCaption: "达到阈值时结束会话并恢复睡眠。",
        keepAwakeSectionMenuBar: "菜单栏",
        keepAwakeShowCountdown: "显示倒计时",
        keepAwakeSectionShortcut: "快捷键",
        keepAwakeEnableShortcut: "启用全局快捷键",
        keepAwakeHotkeyManagerMissing: "快捷键管理器未装载",
        keepAwakeRecord: "录制",
        keepAwakeCancelRecording: "取消录制",
        keepAwakeSectionPointer: "指针微动",
        keepAwakeEnableJiggle: "启用指针微动",
        keepAwakeJiggleInterval: "微动间隔",
        keepAwakeJiggleCaption: "需要辅助功能权限；仅在用户点击申请时触发系统对话框。",
        keepAwakeRequestAccessibility: "申请辅助功能权限",
        keepAwakeSectionClamshell: "合盖",
        keepAwakePreferClamshell: "偏好合盖保持唤醒",
        keepAwakeCapabilityPrefix: "当前能力",
        keepAwakeCapabilityChecking: "检查中",
        keepAwakeCapabilityUnsupportedFormat: "不支持（%@）",
        keepAwakeCapabilityNeedsAuth: "需要授权",
        keepAwakeCapabilityReady: "已就绪",
        keepAwakeCapabilityConflictFormat: "冲突（%@）",
        keepAwakeCapabilityInvalidFormat: "授权无效（%@）",
        keepAwakeConfigureAuth: "配置/重试授权",
        keepAwakeRemoveAuth: "移除授权",
        keepAwakeRefreshStatus: "刷新状态",
        keepAwakeSectionDiagnostics: "诊断",
        keepAwakeDiagSessionFormat: "会话：%@",
        keepAwakeDiagClamshellFormat: "合盖：%@",
        keepAwakeDiagErrorFormat: "最近错误：%@",
        keepAwakeDiagManagerMissing: "Manager 未装载",
        keepAwakeDiagRecoveryFormat: "恢复状态：%@",
        keepAwakeRecoveryIdle: "无需恢复",
        keepAwakeRecoveryRecovered: "已恢复",
        keepAwakeAuthInstallSuccess: "授权安装成功",
        keepAwakeAuthRemoveSuccess: "授权已移除",
        keepAwakeAuthManagerMissingInstall: "Manager 未装载，无法安装授权",
        keepAwakeAuthNoRemoveEntry: "无可用的授权移除入口",
        keepAwakeErrCancelled: "已取消管理员授权",
        keepAwakeErrSudoersFormat: "sudoers 校验失败：%@",
        keepAwakeErrRemovalFormat: "移除授权失败：%@",
        keepAwakeErrBusy: "操作进行中，请稍后重试",
        keepAwakeErrClamshellUnsupportedFormat: "合盖不可用：%@",
        keepAwakeNotifDurationElapsed: "会话已按计划时长结束。",
        keepAwakeNotifLowBattery: "电量达到阈值，会话已结束。",
        keepAwakeNotifCleanupDuration: "会话已结束，但系统睡眠可能未完全恢复。",
        keepAwakeNotifCleanupLowBattery: "电量达到阈值会话已结束，但系统睡眠可能未完全恢复。",
        featureHubRetryUninstall: "重试",
        featureHubUninstallFailedFormat: "卸载失败：%@",
        screenshotEnable: "启用截图",
        screenshotEnableCaption: "启用后，在特性已安装时全局截图快捷键生效。",
        screenshotPermissionSection: "屏幕录制权限",
        screenshotPermissionCaption: "开始任何捕获前必须授予屏幕录制权限。拒绝时会明确失败，不会假装已截图。",
        screenshotRequestPermission: "请求屏幕录制权限",
        screenshotHotkeysSection: "快捷键",
        screenshotHotkeyAllInOne: "全能截图",
        screenshotHotkeyCopy: "截图并复制",
        screenshotHotkeyPin: "截图并贴图",
        screenshotHotkeyFullscreen: "全屏截图",
        screenshotHotkeyRecord: "屏幕录制",
        screenshotOutputSection: "输出",
        screenshotSaveDirectory: "保存目录",
        screenshotChooseDirectory: "选择目录…",
        screenshotPermissionDenied: "未授予屏幕录制权限。请在系统设置中允许捕获。",
        screenshotHotkeyIgnoredNotListening: "截图快捷键当前未在监听。",
        screenshotHotkeyIgnoredUnavailable: "截图特性未安装或不可用。",
        recordingSection: "屏幕录制",
        recordingSaveDirectory: "录屏保存目录",
        recordingChooseDirectory: "选择目录…",
        recordingFormatPreference: "保存格式",
        recordingFormatManual: "每次询问",
        recordingFormatMP4: "MP4",
        recordingFormatGIF: "GIF",
        recordingFormatLabel: "格式",
        recordingFormatChoiceTitle: "保存录屏",
        recordingFormatChoiceMessage: "请选择本次录屏的导出格式。",
        recordingSavePrompt: "保存",
        recordingCancelPrompt: "取消",
        recordingStop: "停止",
        recordingPause: "暂停",
        recordingResume: "继续",
        recordingCancelled: "录屏已取消。",
        recordingExportingGIF: "正在导出 GIF…",
        recordingSavedFormat: "录屏已保存到 %@",
        recordingFailedFormat: "录屏失败：%@",
        screenshotMenuTitle: "截图",
        pinnedMenuTitle: "钉图",
        pinnedMenuEmpty: "无钉图",
        pinnedMenuCopy: "复制",
        pinnedMenuSave: "保存",
        pinnedMenuEnableClickThrough: "开启点击穿透",
        pinnedMenuDisableClickThrough: "关闭点击穿透",
        pinnedMenuLock: "锁定",
        pinnedMenuUnlock: "解锁",
        pinnedMenuClose: "关闭",
        pinnedMenuCloseAll: "关闭全部钉图",
        pinnedMenuActionFailedFormat: "钉图操作失败：%@",
        screenshotSessionAlreadyActive: "已有截图会话进行中。",
        screenshotTargetDisplayUnavailable: "目标显示器不可用。",
        screenshotModeNotImplementedFormat: "截图模式尚未实现：%@",
        screenshotCaptureFailedFormat: "捕获失败：%@",
        screenshotInvalidResultFormat: "无效的捕获结果：%@",
        screenshotInvalidSelectionFormat: "无效选区：%@",
        screenshotPipelineFailedFormat: "结果管线失败：%@",
        screenshotElementRoleWindow: "窗口",
        screenshotElementRoleButton: "按钮",
        screenshotElementRoleMenu: "菜单",
        screenshotElementRoleMenuItem: "菜单项",
        screenshotElementRoleTextField: "文本框",
        screenshotElementRoleSearchField: "搜索框",
        screenshotElementRoleTab: "标签页",
        screenshotElementRoleCheckbox: "复选框",
        screenshotElementRoleRadioButton: "单选项",
        screenshotElementRoleSlider: "滑块",
        screenshotElementRoleListItem: "列表项",
        screenshotElementRoleCell: "单元格",
        screenshotElementRoleToolbarItem: "工具栏",
        screenshotElementRoleGroup: "分组",
        screenshotElementRoleScrollArea: "滚动区域",
        screenshotElementRoleImage: "图像",
        screenshotElementRoleUnknown: "界面元素",
        screenshotElementAccessibilityPermissionMissing: "辅助功能未授权，仅支持窗口吸附和手动框选",
        screenshotElementTargetUnavailable: "目标元素不可用，仅支持窗口吸附和手动框选",
        screenshotElementDetectionFailedFormat: "元素检测失败：%@",
        screenshotFileNamePrefixLabel: "文件名前缀",
        screenshotFileNamePrefixCaption: "作为保存文件名的前缀（时间戳与重复序号保持不变）。",
        screenshotFileNamePrefixInvalid: "文件名前缀不能为空，也不能包含路径分隔符。",
        screenshotCustomPresetsSection: "自定义区域预设",
        screenshotCustomPresetsCaption: "添加的预设会与内置列表一起参与 R / Shift+R 循环；固定尺寸若超出当前屏幕，捕获时自动跳过。",
        screenshotPresetAspectWidth: "比例 宽",
        screenshotPresetAspectHeight: "比例 高",
        screenshotPresetAddAspect: "添加比例",
        screenshotPresetFixedWidth: "固定宽 (px)",
        screenshotPresetFixedHeight: "固定高 (px)",
        screenshotPresetAddFixed: "添加固定尺寸",
        screenshotPresetRemove: "移除",
        screenshotPresetInvalidInput: "宽和高必须是正整数。",
        screenshotPinMenuCopy: "复制",
        screenshotPinMenuSave: "保存",
        screenshotPinMenuLock: "锁定",
        screenshotPinMenuUnlock: "解锁",
        screenshotPinMenuClickThrough: "点击穿透",
        screenshotPinMenuDisableClickThrough: "关闭穿透",
        screenshotPinMenuOpacity: "透明度",
        screenshotPinMenuClose: "关闭",
        screenshotOverlayPresetFree: "自由",
        screenshotOverlayFixedExceedsFormat: "固定尺寸 %d×%d px 超过当前显示器（%d×%d pt @%.1fx）。",
        screenshotOverlayFixedDoesNotFit: "固定尺寸不适合当前显示器。",
        annotationWindowTitle: "标注截图",
        annotationToolSelect: "选择",
        annotationToolArrow: "箭头",
        annotationToolLine: "直线",
        annotationToolRectangle: "矩形",
        annotationToolEllipse: "椭圆",
        annotationToolText: "文字",
        annotationToolFreehand: "画笔",
        annotationToolMosaic: "马赛克",
        annotationToolBlur: "模糊",
        annotationToolRedaction: "遮挡",
        annotationRedactionModePixelate: "像素化",
        annotationRedactionModeBlur: "模糊",
        annotationRedactionModeSolid: "色块",
        annotationToolHighlighter: "荧光笔",
        annotationToolCounter: "编号",
        annotationToolCrop: "裁剪",
        annotationCropHint: "拖动控制点调整裁剪框。确认后写入非破坏裁剪。",
        annotationCropConfirm: "确认裁剪",
        annotationCropCancel: "取消裁剪",
        annotationCropClear: "清除裁剪",
        annotationCropPreset: "裁剪比例",
        annotationCropPresetFreeform: "自由",
        annotationCropPresetOriginal: "原始比例",
        annotationCropPresetSquare: "1:1 正方形",
        annotationCropPreset4x3: "4:3",
        annotationCropPreset3x2: "3:2",
        annotationCropPreset16x9: "16:9",
        annotationCropSnap: "吸附边缘",
        annotationCropSnapHelp: "拖动手柄靠近图像边界时吸附到边缘。按住 ⌘ 可临时关闭。",
        annotationCropWidth: "裁剪宽度（像素）",
        annotationCropHeight: "裁剪高度（像素）",
        annotationCropErrorInvalid: "裁剪区域无效，请调整后重试。",
        annotationCropRotate: "顺时针旋转 90°",
        annotationCropFlipHorizontal: "水平翻转",
        annotationCropFlipVertical: "垂直翻转",
        annotationCropTransformDisabledHelp: "存在标注对象时无法旋转或翻转。请先删除全部标注后再试。",
        annotationBeautifyEnabled: "美化",
        annotationBeautifyBackground: "背景",
        annotationBeautifyBackgroundSolid: "纯色",
        annotationBeautifyBackgroundBlur: "模糊",
        annotationBeautifySolidColor: "颜色",
        annotationBeautifyPadding: "边距",
        annotationBeautifyCornerRadius: "圆角",
        annotationBeautifyShadow: "阴影",
        annotationBeautifyShadowIntensity: "强度",
        annotationStyleStroke: "描边",
        annotationStyleFill: "填充",
        annotationStyleFillColor: "填充色",
        annotationStyleLineWidth: "线宽",
        annotationStyleLineDash: "线型",
        annotationStyleFontSize: "字号",
        annotationTextFill: "背景填充",
        annotationTextOutline: "描边",
        annotationTextTrace: "描边",
        annotationColorCustom: "自定义颜色",
        annotationColorEyedropper: "屏幕取色",
        annotationColorCopyHex: "复制 HEX",
        annotationLineDashSolid: "实线",
        annotationLineDashDashed: "虚线",
        annotationLineDashDotted: "点线",
        annotationActionCopy: "复制",
        annotationActionSave: "保存",
        annotationActionPin: "钉图",
        annotationActionDrag: "拖放",
        tipMoveSelection: "移动选区",
        tipScrollCapture: "长截图",
        tipRecord: "录制选区",
        scrollCaptureAutoScroll: "自动滚动",
        scrollCaptureManualScroll: "手动滚动",
        scrollCaptureHint: "正在滚动…按任意键结束",
        scrollCaptureManualHint: "请滚动页面，然后停止捕获",
        autoScrollPermissionNeeded: "自动滚动需要辅助功能权限。",
        cropLongScreenshotHint: "拖动上下边缘裁剪长截图",
        mergedLongScreenshot: "长截图已就绪",
        tipScrollCropConfirm: "确认裁剪",
        annotationZoomIn: "放大",
        annotationZoomOut: "缩小",
        annotationZoomFit: "适应",
        annotationStatusCopied: "已复制到剪贴板。",
        annotationStatusSaved: "已保存。",
        annotationStatusSavedFormat: "已保存到 %@",
        annotationStatusPinned: "已钉到屏幕。",
        annotationStatusDragReady: "拖放载荷已就绪。",
        annotationErrorNoImage: "没有可用于导出的原图。",
        annotationErrorNoResultMetadata: "缺少截图结果元数据，无法复制/保存。",
        annotationErrorPinNotWired: "钉图不可用。",
        annotationErrorDragNotWired: "拖放不可用。",
        annotationErrorRenderFormat: "渲染失败：%@",
        annotationErrorPipelineFormat: "导出管线失败：%@",
        annotationCloseUnsavedTitle: "丢弃标注？",
        annotationCloseUnsavedMessage: "存在未保存的标注更改。关闭将丢弃这些更改。",
        annotationCloseDiscard: "丢弃",
        annotationCloseCancel: "取消",
        inlineAnnotationFinish: "完成",
        inlineAnnotationCancel: "取消",
        inlineAnnotationErrorMissingSelection: "原位标注需要区域选区。",
        inlineAnnotationErrorModeNotRegion: "原位标注仅适用于区域截图。",
        inlineAnnotationErrorScreenInvalid: "原位标注屏幕快照无效。",
        inlineAnnotationErrorEmptyFrame: "原位标注无法映射出非空窗口 frame。",
        inlineAnnotationErrorInvalidImage: "原位标注原图无效。",
        inlineAnnotationErrorSelectionImageSizeMismatch: "原位标注选区像素尺寸与图像不一致。",
        inlineAnnotationErrorPresenterUnavailable: "原位标注展示器不可用。",
        allInOneToolbarComplete: "完成",
        allInOneToolbarCopy: "复制",
        allInOneToolbarOCR: "OCR",
        allInOneToolbarFullscreen: "全屏",
        allInOneToolbarWindow: "窗口",
        allInOneToolbarScrolling: "滚动",
        allInOneToolbarCancel: "取消",
        captureAnnotationToolShape: "形状",
        captureAnnotationToolLine: "直线/箭头",
        captureAnnotationToolPencil: "画笔",
        captureAnnotationToolHighlighter: "高亮",
        captureAnnotationToolMosaic: "马赛克",
        captureAnnotationToolText: "文字",
        captureAnnotationToolEraser: "橡皮擦",
        captureAnnotationActionUndo: "撤销",
        captureAnnotationActionRedo: "重做",
        captureAnnotationActionCancel: "取消",
        captureAnnotationActionPin: "钉图",
        captureAnnotationActionSave: "保存",
        captureAnnotationActionCopy: "复制",
        captureAnnotationShapeFilledRect: "实心矩形",
        captureAnnotationShapeHollowRect: "空心矩形",
        captureAnnotationShapeEllipse: "椭圆",
        captureAnnotationLineStraight: "直线",
        captureAnnotationLineArrow: "箭头",
        captureAnnotationBrushRound: "圆形笔刷",
        captureAnnotationBrushSquare: "方形笔刷",
        captureAnnotationMosaicPixelate: "像素化",
        captureAnnotationOptionColor: "颜色",
        captureAnnotationOptionSize: "尺寸",
        captureAnnotationOptionMosaicIntensity: "马赛克强度",
        captureAnnotationOptionBold: "粗体",
        captureAnnotationOptionItalic: "斜体",
        captureAnnotationOptionFont: "字体",
        captureAnnotationErrorCopy: "复制失败",
        captureAnnotationErrorSave: "保存失败",
        captureAnnotationErrorPin: "钉图失败",
        captureAnnotationErrorFreeze: "屏幕冻结失败",
        // MARK: - Token Usage
        featureHubNameTokenUsage: "Token 用量",
        featureHubDescTokenUsage: "监控各家 AI CLI 的额度窗口与 token 用量",
        controlcenterTabTokenUsage: "Token",
        controlcenterNavTokenUsage: "Token",
        settingsTabTokenUsage: "Token 用量",
        tokenSettingsCaption: "统计各家 AI CLI 的 token 用量与官方限额窗口，所有数据仅存本机。",
        tokenEmptyHint: "未检测到登录 · 运行一次任一 CLI 即可",
        tokenReauthHint: "登录已失效 · 重新登录对应 CLI 即可",
        tokenRefresh: "刷新",
        tokenProviderAll: "全部",
        tokenWindowSession5h: "5 小时会话窗",
        tokenWindowWeekly: "本周窗口",
        tokenWindowMonthly: "本月窗口",
        tokenWindowCredits: "额外额度",
        tokenWindowCreditsShort: "额度",
        tokenWindowWeeklyShort: "周",
        tokenWindowPlanShort: "套餐",
        tokenWindowAutoShort: "自动",
        tokenStatusNormal: "正常",
        tokenStatusApproaching: "接近限额",
        tokenStatusExceeded: "已超额",
        tokenStatusReauth: "需重新登录",
        tokenStatusRateLimited: "请求过于频繁",
        tokenStatusStale: "数据可能过期",
        tokenErrorNetwork: "网络错误",
        tokenErrorTransient: "暂时无法获取",
        tokenRateLimitedCaptionFormat: "请求过于频繁，%@ 前可重试",
        tokenErrorRetryableHint: "可重试",
        tokenBackfilling: "正在统计历史用量…",
        tokenCreditsRemainingFormat: "剩 %@",
        tokenResetInApproxFormat: "重置于 %@",
        tokenPaceOver: "按当前步速将提前用尽",
        tokenPaceProjectedFormat: "重置时预计用量 %d%%",
        tokenCreditCaption: "随订阅周期自动补充 · 官方数据",
        tokenResetBankTitle: "重置权益",
        tokenResetBankEntryFormat: "重置 %d · %@ 过期",
        tokenResetBankCountOnlyFormat: "重置权益：%d 次 · 过期时间不可用",
        tokenUpdatedJustNow: "刚刚更新",
        tokenUpdatedMinutesFormat: "%d 分钟前更新",
        tokenUpdatedHoursFormat: "%d 小时前更新",
        tokenSourceOfficial: "官方来源",
        tokenFooterFormat: "%@ · %@ · %d 家已配置 %d 家",
        tokenUsageLocalFormat: "本地统计 · 每 %d 分钟汇总",
        tokenSummaryToday: "今日",
        tokenSummarySevenDays: "7 天",
        tokenSummaryThirtyDays: "30 天",
        tokenSummaryTotal: "总计",
        tokenSummaryConversationsFormat: "%d 会话",
        tokenSummaryActiveDaysFormat: "%d 活跃日",
        tokenSummaryAvgPerDayFormat: "~%@/天",
        tokenActivityTitle: "活跃度",
        tokenActivityLegendLess: "少",
        tokenActivityLegendMore: "多",
        tokenTrendTitle: "趋势",
        tokenTrendPeriodDay: "日",
        tokenTrendPeriodWeek: "周",
        tokenTrendPeriodMonth: "月",
        tokenTrendPeriodTotal: "总计",
        tokenTopModelsTitle: "模型",
        tokenUnit: "tokens",
        tokenSettingsGenericSection: "通用",
        tokenSettingsProvidersSection: "提供商",
        tokenSettingsAlertsSection: "告警",
        tokenSettingsMenuBarMode: "菜单栏显示",
        tokenSettingsMenuBarToday: "今日 tokens",
        tokenSettingsMenuBarSession: "会话窗用量 %",
        tokenSettingsMenuBarOff: "关闭",
        tokenMenuBarTodayLabel: "今日",
        tokenSettingsRefreshInterval: "限额刷新间隔",
        tokenSettingsRefreshMinuteFormat: "%d 分钟",
        tokenSettingsLimitsDisplay: "限额显示",
        tokenSettingsLimitsUsed: "已用",
        tokenSettingsLimitsRemaining: "剩余",
        tokenResetToastLabel: "额度重置时显示提示",
        tokenResetConfettiLabel: "额度重置时撒花",
        tokenResetCelebrationFormat: "%@ 额度已重置 🎉",
        tokenSettingsDefaultPeriod: "用量统计周期默认",
        tokenSettingsProviderStatusFormat: "%@ · %@",
        tokenSettingsLoggedIn: "已登录",
        tokenSettingsNotConfigured: "未登录",
        tokenSettingsHowToConfigure: "如何配置",
        tokenSettingsNoSubscription: "未开通套餐",
        tokenSettingsNoQuotaAvailable: "无有效配额",
        tokenSettingsManageMoreProviders: "管理更多提供商…",
        tokenSettingsSessionAlertFormat: "会话窗用量 ≥%g%% 时通知",
        tokenSettingsAlertThreshold: "会话窗告警阈值",
        tokenSettingsAlertThresholdFormat: "%g%%",
        tokenSettingsPaceAlert: "步速超前时通知",
        tokenSettingsRequestPermission: "申请通知权限",
        tokenSettingsPermissionGranted: "已授权",
        tokenSettingsPermissionDenied: "未授权",
        tokenSettingsConfigureHintFormat: "运行一次 `%@` 登录后自动识别",
        tokenSettingsConfigureHintCursor: "在 Cursor 应用内登录后自动识别",
        tokenSettingsConfigureHintAntigravity: "启动 Antigravity 后，IDE 运行期间自动读取限额",
        tokenSettingsConfigureHintTraeCn: "在下方设置中粘贴 Trae CN 的 JWT，仅保存到 macOS 钥匙串",
        tokenMenuBarSessionLabel: "会话窗",
        tokenAlertSessionTitle: "Token 用量告警",
        tokenAlertSessionBodyFormat: "%@ 会话窗用量已达 %d%%，可能提前耗尽。",
        tokenAlertPaceTitle: "Token 用量步速超前",
        tokenAlertPaceBodyFormat: "按当前步速，%@ 会话窗将在重置前用尽。",
        tokenDurationDayFormat: "%d 天",
        tokenDurationHourFormat: "%d 小时",
        tokenDurationMinuteFormat: "%d 分钟",
        tokenWeekdayNames: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
        deepSeekBalanceCardTitle: "DeepSeek 余额",
        deepSeekBalanceLoading: "正在获取余额…",
        deepSeekBalanceUnavailable: "余额暂不可用",
        deepSeekStatusBelowThreshold: "低于阈值",
        deepSeekStatusReauthKey: "密钥已失效",
        deepSeekBalanceFooterFormat: "%@ · %@",
        deepSeekAlertTitle: "DeepSeek 余额告警",
        deepSeekAlertBodyFormat: "DeepSeek 余额仅剩 %@，低于阈值 %@。",
        tokenSettingsTraeCnSection: "Trae CN",
        tokenSettingsTraeCnJwtPlaceholder: "粘贴你的 Cloud-IDE-JWT…",
        opencodeSettingsApiKeyPlaceholder: "粘贴你的 OpenCode Go API Key…",
        opencodeSettingsApiKeyCaption: "密钥仅保存在 macOS 钥匙串，不写入磁盘",
        arkSettingsAkPlaceholder: "粘贴你的 AccessKey ID (AK)…",
        arkSettingsSkPlaceholder: "粘贴你的 SecretAccessKey (SK)…",
        arkSettingsCaption: "密钥仅保存在 macOS 钥匙串，用于直接请求火山方舟 OpenAPI 查询 Coding Plan 限额（需已在火山引擎开通 Coding Plan 套餐），无需安装 arkcli",
        deepSeekSettingsApiKeyPlaceholder: "sk-...",
        tokenSettingsApiKeyTitle: "API Key",
        deepSeekSettingsSaveKey: "保存",
        deepSeekSettingsClearKey: "清除",
        deepSeekSettingsKeySaved: "密钥已保存到钥匙串",
        deepSeekSettingsKeyMissing: "未配置密钥",
        deepSeekSettingsApiKeyCaption: "密钥仅保存在 macOS 钥匙串，不写入磁盘",
        deepSeekSettingsApiKeyInvalid: "密钥无效，请检查后重试",
        deepSeekSettingsLowBalanceAlert: "低余额通知",
        deepSeekSettingsLowBalanceAlertToggle: "余额低于阈值时通知",
        deepSeekSettingsThresholdLabel: "阈值（¥）",
        deepSeekSettingsThresholdHint: "余额低于阈值时通知一次；充值恢复后重新计数",
        deepSeekSettingsThresholdInvalid: "请输入有效金额（大于 0）",
        deepSeekSettingsRefreshInterval: "余额刷新间隔",
        featureHubNameProviderSwitch: "供应商切换",
        featureHubDescProviderSwitch: "切换 Claude Code / Codex 的上游 API 供应商，只写入供应商拥有的字段",
        featureHubGroupAI: "AI",
        settingsTabProviderSwitch: "供应商切换",
        controlcenterTabProviderSwitch: "供应商",
        controlcenterNavProviderSwitch: "供应商",
        providerToolClaudeCode: "Claude Code",
        providerToolCodex: "Codex",
        providerOfficial: "官方",
        providerOfficialClaudeCaption: "Anthropic 官方 API",
        providerOfficialCodexCaption: "OpenAI 官方 API",
        providerSwitchBackToOfficial: "切换到官方",
        providerActiveProfileFormat: "已激活：%@",
        providerActiveUnmanagedTitle: "未托管配置",
        providerActiveUnmanagedSummaryFormat: "检测到配置文件中的未托管设置：%@",
        providerActiveUnreadableTitle: "配置文件损坏",
        providerActiveUnreadableCaption: "已检测到损坏，未写入任何内容；可备份并重建",
        providerSetActive: "设为激活",
        providerActiveMark: "已激活",
        providerInUseBadge: "使用中",
        providerEdit: "编辑",
        providerDelete: "删除",
        providerAddProvider: "+ 新增供应商",
        providerAddProfileFormat: "新增 %@ 供应商",
        providerEmptyProfilesHint: "暂无供应商档案，点「新增」从预设或自定义创建",
        providerUnmanagedAdopt: "收编为供应商",
        providerUnmanagedAdoptPrompt: "为此未托管配置命名",
        providerUnmanagedAdoptPlaceholder: "供应商名称",
        providerUnmanagedAdoptError: "缺少 Base URL 或凭证，无法收编",
        providerCorruptedBackupAndRebuild: "备份并重建",
        providerCorruptedRebuildConfirmTitle: "备份并重建？",
        providerCorruptedRebuildConfirmMessage: "将把损坏的配置文件移到备份目录，再重新创建。",
        providerSwitchDoneFormat: "已切换到 %@",
        providerSwitchDoneOfficial: "已切换回官方",
        providerRestartHint: "切换后需重启 CLI 生效",
        providerRestartRunningHintFormat: "%@ 正在运行，需重启后才生效",
        providerSwitchFailedFormat: "切换失败：%@",
        providerEditConfigFile: "编辑配置文件",
        providerRestoreBackup: "恢复备份",
        providerBackupRestored: "已从备份恢复",
        providerDeleteConfirmTitle: "删除供应商？",
        providerDeleteConfirmMessageFormat: "将删除「%@」及其保存的凭证，此操作不可撤销。",
        providerDeleteConfirmButton: "删除",
        providerNameLabel: "名称",
        providerBaseURLLabel: "Base URL",
        providerTokenLabel: "凭证",
        providerTokenPlaceholder: "粘贴 API Key…",
        providerModelLabel: "模型（可选）",
        providerModelHint: "留空使用供应商默认模型",
        providerSmallFastModelLabel: "小模型（可选）",
        providerPresetLabel: "预设",
        providerPresetNone: "自定义",
        providerFormNameConflict: "已存在同名供应商，请更换名称",
        providerFormSave: "保存",
        providerFormCancel: "取消",
        providerFormTitleNewFormat: "新增 %@ 供应商",
        providerFormTitleEditFormat: "编辑 %@ 供应商",
        providerEditorTitleFormat: "编辑 %@ 配置文件",
        providerEditorInvalidContent: "内容不是合法 JSON/TOML，已拒绝保存",
        providerEditorSaved: "已保存",
        providerEditorHint: "原文编辑不受字段所有权保护；保存前校验合法性，非法拒绝保存",
        providerBackupListTitle: "历史备份",
        providerBackupEmpty: "暂无备份",
        providerBackupRestoreConfirmTitle: "恢复此备份？",
        providerBackupRestoreConfirmMessageFormat: "将用备份「%@」覆盖当前配置文件。",
        providerBackupRestore: "恢复",
        providerBackupRestoreFailed: "恢复失败，请稍后重试"
    )
}
